---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Mi
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: seerr-config-backup
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: seerr-config-backup
spec:
  sourcePVC: seerr-config
  trigger:
    schedule: "0 6 * * *"
  restic:
    pruneIntervalDays: 7
    repository: restic-config-seerr-config
    retain:
      hourly: 4
      daily: 7
      weekly: 1
    copyMethod: Clone
    storageClassName: longhorn-local
    cacheStorageClassName: longhorn-local
    cacheCapacity: 10Mi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: seerr-config-backup
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-config-seerr-config
    copyMethod: Snapshot
    accessModes:
    - ReadWriteOnce
    capacity: 16Mi
    cleanupCachePVC: true
    cleanupTempPVC: true
    enableFileDeletion: true
    storageClassName: longhorn-local
    cacheStorageClassName: longhorn-local
    cacheCapacity: 10Mi
