apiVersion: v1
kind: Secret
metadata:
    name: restic-config-seerr-config
stringData:
    RESTIC_REPOSITORY: s3:https://fsn1.your-objectstorage.com/volsync-restic/seerr-config
    RESTIC_PASSWORD: LaSrHLAnGBqkc2nJaxV5zVu2k
    AWS_ACCESS_KEY_ID: UYCTUEM42OCKZ2X18BO2
    AWS_SECRET_ACCESS_KEY: 1isuIMQRsH11Y6gjNJO2D5wbgzK3xaVFgz7ueFFi
