---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- hr-arrs.yaml
- secret-arrs.sops.yaml
- pvc-arrs-config.yaml
- pvc-arrs-downloads.yaml
- pvc-arrs-media.yaml
configMapGenerator:
  - name: recyclarr-config-file
    files:
      - recyclarr.yml=./resources/recyclarr-config.yaml
generatorOptions:
  disableNameSuffixHash: true
