---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-data
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: radarr-data-backup
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: radarr-data-backup
spec:
  sourcePVC: radarr-data
  trigger:
    schedule: "0 * * * *"
  restic:
    pruneIntervalDays: 7
    repository: restic-config-radarr-data
    retain:
      hourly: 4
      daily: 7
      weekly: 1
    copyMethod: Clone
    storageClassName: longhorn-local
    cacheStorageClassName: longhorn-local
    moverPodLabels:
      setGateway: "false"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: radarr-data-backup
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-config-radarr-data
    copyMethod: Snapshot
    accessModes:
    - ReadWriteOnce
    capacity: 128Mi
    cleanupCachePVC: true
    cleanupTempPVC: true
    enableFileDeletion: true
    storageClassName: longhorn-local
    cacheStorageClassName: longhorn-local
    moverPodLabels:
      setGateway: "false"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: sonarr-data-backup
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sonarr-data-backup
spec:
  sourcePVC: sonarr-data
  trigger:
    schedule: "0 * * * *"
  restic:
    pruneIntervalDays: 7
    repository: restic-config-sonarr-data
    retain:
      hourly: 4
      daily: 7
      weekly: 1
    copyMethod: Clone
    storageClassName: longhorn-local
    cacheStorageClassName: longhorn-local
    moverPodLabels:
      setGateway: "false"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: sonarr-data-backup
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-config-sonarr-data
    copyMethod: Snapshot
    accessModes:
    - ReadWriteOnce
    capacity: 256Mi
    cleanupCachePVC: true
    cleanupTempPVC: true
    enableFileDeletion: true
    storageClassName: longhorn-local
    cacheStorageClassName: longhorn-local
    moverPodLabels:
      setGateway: "false"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-data
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Mi
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: bazarr-data-backup
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: bazarr-data-backup
spec:
  sourcePVC: bazarr-data
  trigger:
    schedule: "0 * * * *"
  restic:
    pruneIntervalDays: 7
    repository: restic-config-bazarr-data
    retain:
      hourly: 4
      daily: 7
      weekly: 1
    copyMethod: Clone
    storageClassName: longhorn-local
    cacheStorageClassName: longhorn-local
    moverPodLabels:
      setGateway: "false"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: bazarr-data-backup
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-config-bazarr-data
    copyMethod: Snapshot
    accessModes:
    - ReadWriteOnce
    capacity: 8Mi
    cleanupCachePVC: true
    cleanupTempPVC: true
    enableFileDeletion: true
    storageClassName: longhorn-local
    cacheStorageClassName: longhorn-local
    moverPodLabels:
      setGateway: "false"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-data
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: prowlarr-data-backup
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: prowlarr-data-backup
spec:
  sourcePVC: prowlarr-data
  trigger:
    schedule: "0 * * * *"
  restic:
    pruneIntervalDays: 7
    repository: restic-config-prowlarr-data
    retain:
      hourly: 4
      daily: 7
      weekly: 1
    copyMethod: Clone
    storageClassName: longhorn-local
    cacheStorageClassName: longhorn-local
    moverPodLabels:
      setGateway: "false"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: prowlarr-data-backup
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-config-prowlarr-data
    copyMethod: Snapshot
    accessModes:
    - ReadWriteOnce
    capacity: 256Mi
    cleanupCachePVC: true
    cleanupTempPVC: true
    enableFileDeletion: true
    storageClassName: longhorn-local
    cacheStorageClassName: longhorn-local
    moverPodLabels:
      setGateway: "false"
