apiVersion: v1
kind: Secret
metadata:
    name: restic-config-radarr-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:FMmubPl2IvX44Mh1GeUhsduzMJjzj4Ntjd2NYzQ7cpl6Lf0qfnsNwKhIsdu06uPC2zJZLOolXLiHt7jm/JKr,iv:v7Sb7vYeR6/u9JndRdO8gGPeO9wEAo+ZhuxPKJsMj8o=,tag:ymSpiajTMhSExF9gVQ8pbQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:/+l9M4Vlczz638Him63CSBru/EMqcsedOQ==,iv:xhaZ4py8RmYNREiS1EXLlLYJma6GbV8wc5JndNuVbv4=,tag:4OhfS2BJXMwPtbbuujwf1g==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:qOb6uHtXPessRxHVQybn97TAc5Q=,iv:39s3qyLqRyi0RfSaIxl7iYjQLNiW3s4IQjKNHUxJGX0=,tag:dChCKtpJj/fzb40jHJkakg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:VMjwPVXUljG3k5rdDtjrLwoeyOBVJtH3Nt7cCh9JpXLDO+8Vy2iSXg==,iv:PZ1Ip0pizLaKvbNWbWJB/5tt5Xyo9Y3GnN+8Wgt3oOc=,tag:rSJVPjoUCQ/nwSvuFS4Qkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVEdKYWEzUmtLZjFwdHdr
            aVI4a0FrL053SURBZWhaUWxoR0xTQ2FXcW1RCkVmMkhjd1dpUDlXVUU5Q1NZS2hl
            VzZURGloQnN6a2VmSmtkMTNTckZiVVEKLS0tIHUxdTd5M0ZMZThNSWw2OE1RR1Jo
            bHZiMTdBN3Q3Q2c2TFd5MlRVNnhhaDgKNO0vALlMIrEai0So1c8ruSnIDzpaw6m9
            pblHhpov1ujjPJmJk1uUgRC5+gtQ/hUYQVBWbYH4FPdHyr/XJU6szA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T13:22:33Z"
    mac: ENC[AES256_GCM,data:9csv6ryM/4uI4rL0BjIl4YM/ZTn37A7yEPeLT7VjB2373S7e8qJCYcyboXRsDW2L3Sx9bl9ftK/N+sE/0CbCebsDWzG6ZCZ36OjQB3IArZ94IeXz6kqb5wQmKUuNW978e2Sd/B7+c6HteCdev8/Cd2su8QnHbtZSprPhSVjUO6c=,iv:DCGTMQ+VEfpg1gT9jCzC4QxnNognZjgtK4SFciR8qOs=,tag:KnEgr7VcnsLF/OhTP/6JsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-sonarr-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:L1ORXbRBi9+bT9xtJA7Vb97svSFOwx5P/wJDdMg31qf1lWtNpoUY0W5KHTmPhijkOrupii+5wTUazh1IA0LZ,iv:2tOX/XS28E9UjJPXrksfj1Rfj6qYhoqZ/Mzocdb1c78=,tag:BxAA0KU7ekK7FIVtDAWIDA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:VyS7sYkrbtMEVTcZ+k6gld9nG7ZRJ5Lz9g==,iv:c9sfZFYheXbxjc3O46Z3WFI4/JpGayBBT4+D+WoSdzY=,tag:GtajE5IuVWteF1d+fb9RBQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:yIAtZ06/GwkZHQOgASChBZsDmeA=,iv:TzdH2t/SDbROc9RQj7L05i1XIfRKEqzQPM0IdrsX1Fk=,tag:Gc5vU7QUte++N5kMuQzmzQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ozwxi36175zr8RvSfB90bzzcM/1m55717ekzsnz4nm4OjhEuAeLC7g==,iv:nI0GOVWS7UebuBSbBc18DC80TJLHnjyr9f0heHw9HBs=,tag:XR3XIGlEkHLkMAi/C88JMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVEdKYWEzUmtLZjFwdHdr
            aVI4a0FrL053SURBZWhaUWxoR0xTQ2FXcW1RCkVmMkhjd1dpUDlXVUU5Q1NZS2hl
            VzZURGloQnN6a2VmSmtkMTNTckZiVVEKLS0tIHUxdTd5M0ZMZThNSWw2OE1RR1Jo
            bHZiMTdBN3Q3Q2c2TFd5MlRVNnhhaDgKNO0vALlMIrEai0So1c8ruSnIDzpaw6m9
            pblHhpov1ujjPJmJk1uUgRC5+gtQ/hUYQVBWbYH4FPdHyr/XJU6szA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T13:22:33Z"
    mac: ENC[AES256_GCM,data:9csv6ryM/4uI4rL0BjIl4YM/ZTn37A7yEPeLT7VjB2373S7e8qJCYcyboXRsDW2L3Sx9bl9ftK/N+sE/0CbCebsDWzG6ZCZ36OjQB3IArZ94IeXz6kqb5wQmKUuNW978e2Sd/B7+c6HteCdev8/Cd2su8QnHbtZSprPhSVjUO6c=,iv:DCGTMQ+VEfpg1gT9jCzC4QxnNognZjgtK4SFciR8qOs=,tag:KnEgr7VcnsLF/OhTP/6JsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-bazarr-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:yAwgM/w21yaZEfPc4AcgpGHAeRxG7WNc+b6oIksbVrEbR6lfkbSmPsEiEtJANf2xMKOlW4aEm+lujc5WK+8S,iv:RE3gQnRDY8P2eWq5Xje2FjvCJWuZ0uiL1FqmqXi21IY=,tag:sfpPZevbNqnZNHpTJzZB0A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:GIMl1Bpe6zeWrEZqsXdA1N0vqBm92wGSZg==,iv:loo26I31qEvroP/azwQxlXWArmfJeua0DpLnAtXyWng=,tag:fIlO7tRuBGx/VMQwoia83g==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ogBtWv+0NPYw3PG80ZiyfabRdlU=,iv:TxvzNK18L1i5Wq8DqJpVuoR4dFUyFiLjlK/eEWLtJ5s=,tag:jNBPn6z1j6eBCv5B3zGZIw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:eQQ6fGuVoCAUQkd9hBlo+bQ/PCDoj1qHODXP1jxYaRHa0Vx0t3c6yQ==,iv:RqQDsh6VZsjhoz3Ny3BmEIDztMM1XtyOTSQR15wNTyE=,tag:tT+c7nH5EPattUfk6WnRFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVEdKYWEzUmtLZjFwdHdr
            aVI4a0FrL053SURBZWhaUWxoR0xTQ2FXcW1RCkVmMkhjd1dpUDlXVUU5Q1NZS2hl
            VzZURGloQnN6a2VmSmtkMTNTckZiVVEKLS0tIHUxdTd5M0ZMZThNSWw2OE1RR1Jo
            bHZiMTdBN3Q3Q2c2TFd5MlRVNnhhaDgKNO0vALlMIrEai0So1c8ruSnIDzpaw6m9
            pblHhpov1ujjPJmJk1uUgRC5+gtQ/hUYQVBWbYH4FPdHyr/XJU6szA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T13:22:33Z"
    mac: ENC[AES256_GCM,data:9csv6ryM/4uI4rL0BjIl4YM/ZTn37A7yEPeLT7VjB2373S7e8qJCYcyboXRsDW2L3Sx9bl9ftK/N+sE/0CbCebsDWzG6ZCZ36OjQB3IArZ94IeXz6kqb5wQmKUuNW978e2Sd/B7+c6HteCdev8/Cd2su8QnHbtZSprPhSVjUO6c=,iv:DCGTMQ+VEfpg1gT9jCzC4QxnNognZjgtK4SFciR8qOs=,tag:KnEgr7VcnsLF/OhTP/6JsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-prowlarr-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:O8NUuBabbbAC6z2mN9tYKxrhuk4/iTatd9W2yphkVWhStmaGosQnWeJA0XQ+q91IVfv+xGZp09wTIaiJYJye8N0=,iv:yqPRHosX1WMnDf1FR29J2nMmGcOyWkeU/eqrD5bK4i4=,tag:vBydvBj5rmMbIfXy4fzriA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:LPiBHb9vlDRrL08kSg4/wcjNGU6bCAyTyA==,iv:cM1PscwFUqF3MH4EKAnUaI9n1C4neqeojXZyinvr/gY=,tag:UFi/e1tFa/ypAmRuFPl8WA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:qxLer3S76gw+ycTIGvd6CdINA+w=,iv:RAyW8E64xO0daz7jukeM+scelAB8T/jC/0K20vW+M6s=,tag:ATYmAE3i9/ol/tYnw9J0ng==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:MYw1uKKn34WoyNp6kNlCcqEXLM1z79pIf5tnNrZmTGPQ5M8Yw2h7Wg==,iv:HKuGUK3FktGKWz/lyqc2ico8w0xOyGtgyz2/6nsiqX4=,tag:6RMHGALs+zoP9zMAb2y6Yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVEdKYWEzUmtLZjFwdHdr
            aVI4a0FrL053SURBZWhaUWxoR0xTQ2FXcW1RCkVmMkhjd1dpUDlXVUU5Q1NZS2hl
            VzZURGloQnN6a2VmSmtkMTNTckZiVVEKLS0tIHUxdTd5M0ZMZThNSWw2OE1RR1Jo
            bHZiMTdBN3Q3Q2c2TFd5MlRVNnhhaDgKNO0vALlMIrEai0So1c8ruSnIDzpaw6m9
            pblHhpov1ujjPJmJk1uUgRC5+gtQ/hUYQVBWbYH4FPdHyr/XJU6szA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T13:22:33Z"
    mac: ENC[AES256_GCM,data:9csv6ryM/4uI4rL0BjIl4YM/ZTn37A7yEPeLT7VjB2373S7e8qJCYcyboXRsDW2L3Sx9bl9ftK/N+sE/0CbCebsDWzG6ZCZ36OjQB3IArZ94IeXz6kqb5wQmKUuNW978e2Sd/B7+c6HteCdev8/Cd2su8QnHbtZSprPhSVjUO6c=,iv:DCGTMQ+VEfpg1gT9jCzC4QxnNognZjgtK4SFciR8qOs=,tag:KnEgr7VcnsLF/OhTP/6JsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
