apiVersion: v1
kind: Secret
metadata:
    name: restic-config-radarr-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:RiGRzwlr0Vv9d7DJMFjg/bov+GHhgMmEFdmohbFEAWLLt8EeUQTE8fhu/O6+qfr+KouXBUOk8ONwnkDNqifeaGc=,iv:ZsKtKihD4Cc+2iKXMcLTKPIGg7gbyH2oBtzOXqhfAjo=,tag:rBfKirzNcJ77/YkP4HPocw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:LPiBHb9vlDRrL08kSg4/wcjNGU6bCAyTyA==,iv:cM1PscwFUqF3MH4EKAnUaI9n1C4neqeojXZyinvr/gY=,tag:UFi/e1tFa/ypAmRuFPl8WA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:yiX0Z7/gGt+GPFmB0tJJNo9FVok=,iv:Ows358Dv7ZGl0nY76Qootfo9JUMMS+wB/jCBqvlm6iM=,tag:5Qrj+66Rjw7Laou1jIc+ag==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aHxv/8I3pSv25817I+kUorRLwP5ZVtEqnYSW6A37nSP5hGA/2qKInQ==,iv:lKN8Bjw3vf5sOkFcEYUph9kGzuOgqeMVJ0qlThdrw5k=,tag:eAHimZeuT+ahZZyPecntdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVEdKYWEzUmtLZjFwdHdr
            aVI4a0FrL053SURBZWhaUWxoR0xTQ2FXcW1RCkVmMkhjd1dpUDlXVUU5Q1NZS2hl
            VzZURGloQnN6a2VmSmtkMTNTckZiVVEKLS0tIHUxdTd5M0ZMZThNSWw2OE1RR1Jo
            bHZiMTdBN3Q3Q2c2TFd5MlRVNnhhaDgKNO0vALlMIrEai0So1c8ruSnIDzpaw6m9
            pblHhpov1ujjPJmJk1uUgRC5+gtQ/hUYQVBWbYH4FPdHyr/XJU6szA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:35:03Z"
    mac: ENC[AES256_GCM,data:Sagb6rVHKyACQPzzwZNER7YuaupGBA03aOMUNXSi4llH8m4oTL1bSyLd5BuXO6kcBsfgr1emL8RxDwIJYvu8ZVvC1/rhzglgqPZD1aUGLDf7TF85A3siNjj7r83aOrNgUlT0Y/vhAfjQbsVrZW4pie8R5IIyX4C/LZ0XwezEV4E=,iv:ZOItyoc9jsli91pFP5mwnX2dspkxRBe2VWJZkCM2h34=,tag:iYMo1FMoeXvcVZc3zO84ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-sonarr-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:6Fh7fMWufrnv1fQG//7xAxKCTuXE1MVdE0OdWrLBCorAh/lYrl4exnsrl0fGLU81p/zy3eJ+vS3IIWSIPhSM598=,iv:HMFhXJTj3VzsqcI+OGzJLYgCoxnISu8PNkv0lpJBvuk=,tag:ZU2rOwoDxxEDNC/RxBhdBg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:LPiBHb9vlDRrL08kSg4/wcjNGU6bCAyTyA==,iv:cM1PscwFUqF3MH4EKAnUaI9n1C4neqeojXZyinvr/gY=,tag:UFi/e1tFa/ypAmRuFPl8WA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZhJ5V3wUWa7xvAZVARXOrYccVGE=,iv:424rXttVVJv8aCzZwIZfy89RNSYS25g6UQXDkQbtHfQ=,tag:XNK+J6y7EcqeNDLE14bz8w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/QASQJoJgUfFvQ3x4zgp8hi9Cg3kuQBMZm3kWt3W4hNPXfM4yM3kAw==,iv:+do9ejANh0Uj2ANWh1Qe9Q9aWm0BwzY3FHhji5G5Mlc=,tag:vmjM7Scm/6fZ1o2Wg//qxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVEdKYWEzUmtLZjFwdHdr
            aVI4a0FrL053SURBZWhaUWxoR0xTQ2FXcW1RCkVmMkhjd1dpUDlXVUU5Q1NZS2hl
            VzZURGloQnN6a2VmSmtkMTNTckZiVVEKLS0tIHUxdTd5M0ZMZThNSWw2OE1RR1Jo
            bHZiMTdBN3Q3Q2c2TFd5MlRVNnhhaDgKNO0vALlMIrEai0So1c8ruSnIDzpaw6m9
            pblHhpov1ujjPJmJk1uUgRC5+gtQ/hUYQVBWbYH4FPdHyr/XJU6szA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:35:03Z"
    mac: ENC[AES256_GCM,data:Sagb6rVHKyACQPzzwZNER7YuaupGBA03aOMUNXSi4llH8m4oTL1bSyLd5BuXO6kcBsfgr1emL8RxDwIJYvu8ZVvC1/rhzglgqPZD1aUGLDf7TF85A3siNjj7r83aOrNgUlT0Y/vhAfjQbsVrZW4pie8R5IIyX4C/LZ0XwezEV4E=,iv:ZOItyoc9jsli91pFP5mwnX2dspkxRBe2VWJZkCM2h34=,tag:iYMo1FMoeXvcVZc3zO84ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-bazarr-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Qu5N5F6AsGU9n+5HTyo7jmaXZffuHAIBaxoGMtR1B7a/i3ZN24o3+bdxr1Eulrmww2bxcyGO+VAEBhpzAyNo5jY=,iv:L0G/tFVL+4tGKAiPEzcoJz3UgQgy80LPgMFuyv6hlKU=,tag:7jXjxBDMo96o+K9/NikNaA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:LPiBHb9vlDRrL08kSg4/wcjNGU6bCAyTyA==,iv:cM1PscwFUqF3MH4EKAnUaI9n1C4neqeojXZyinvr/gY=,tag:UFi/e1tFa/ypAmRuFPl8WA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:AxZbg+i5BEZh3wzQ2EMgsqHaL3Q=,iv:E09QYIJgmBI5fi29QIrzF69IvbwS0S8GHwiTC7WvJXA=,tag:lorwK0UmqRVweDAKIfKTNg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/fvay0Zl51QTvqkfruftqSBEK2JWM+oTCRIfc/kyaYK26lo8LSPV9A==,iv:JaUMXZQJryAKy3MhzC5Jq62X4HyQQwOcMvchypN35qM=,tag:vX59huFSpjqeuf3vSSauqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVEdKYWEzUmtLZjFwdHdr
            aVI4a0FrL053SURBZWhaUWxoR0xTQ2FXcW1RCkVmMkhjd1dpUDlXVUU5Q1NZS2hl
            VzZURGloQnN6a2VmSmtkMTNTckZiVVEKLS0tIHUxdTd5M0ZMZThNSWw2OE1RR1Jo
            bHZiMTdBN3Q3Q2c2TFd5MlRVNnhhaDgKNO0vALlMIrEai0So1c8ruSnIDzpaw6m9
            pblHhpov1ujjPJmJk1uUgRC5+gtQ/hUYQVBWbYH4FPdHyr/XJU6szA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:35:03Z"
    mac: ENC[AES256_GCM,data:Sagb6rVHKyACQPzzwZNER7YuaupGBA03aOMUNXSi4llH8m4oTL1bSyLd5BuXO6kcBsfgr1emL8RxDwIJYvu8ZVvC1/rhzglgqPZD1aUGLDf7TF85A3siNjj7r83aOrNgUlT0Y/vhAfjQbsVrZW4pie8R5IIyX4C/LZ0XwezEV4E=,iv:ZOItyoc9jsli91pFP5mwnX2dspkxRBe2VWJZkCM2h34=,tag:iYMo1FMoeXvcVZc3zO84ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-prowlarr-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:bdd8ZxzW34XmqGCrgIL4n5wS9nhbrOTuxirILNNkeTUDdTGpMfQegeBI6zA6o0R+ZTrioyhDQRLQ+vxV/30JIIvpbw==,iv:Kswudr+Vv97AyMEU/036xVc4o+udNqmHoZMheE3jgyc=,tag:C3ZLMiOJN0qsxpCL+h6gSA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:LPiBHb9vlDRrL08kSg4/wcjNGU6bCAyTyA==,iv:cM1PscwFUqF3MH4EKAnUaI9n1C4neqeojXZyinvr/gY=,tag:UFi/e1tFa/ypAmRuFPl8WA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:SEyHLkQz/igPrXkbdn0RFTaD9Ps=,iv:HhYB9ewV9C34gVkQ52LZr+NhpPja8nqQmwMDv1dX/ZI=,tag:R+5GEaBQf13soYfYxEvX6Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Tkwb3Z+Ur2TwRDemT9zekFlszf3ZF8DQisGmEeAbGnXyszogJqQOSg==,iv:EBrUJ65UcgO8WNTMMKwQFgGrR16StMr1hy+hiLmE3Ec=,tag:6GoY1KT+EpgTna0goEPnDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVEdKYWEzUmtLZjFwdHdr
            aVI4a0FrL053SURBZWhaUWxoR0xTQ2FXcW1RCkVmMkhjd1dpUDlXVUU5Q1NZS2hl
            VzZURGloQnN6a2VmSmtkMTNTckZiVVEKLS0tIHUxdTd5M0ZMZThNSWw2OE1RR1Jo
            bHZiMTdBN3Q3Q2c2TFd5MlRVNnhhaDgKNO0vALlMIrEai0So1c8ruSnIDzpaw6m9
            pblHhpov1ujjPJmJk1uUgRC5+gtQ/hUYQVBWbYH4FPdHyr/XJU6szA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:35:03Z"
    mac: ENC[AES256_GCM,data:Sagb6rVHKyACQPzzwZNER7YuaupGBA03aOMUNXSi4llH8m4oTL1bSyLd5BuXO6kcBsfgr1emL8RxDwIJYvu8ZVvC1/rhzglgqPZD1aUGLDf7TF85A3siNjj7r83aOrNgUlT0Y/vhAfjQbsVrZW4pie8R5IIyX4C/LZ0XwezEV4E=,iv:ZOItyoc9jsli91pFP5mwnX2dspkxRBe2VWJZkCM2h34=,tag:iYMo1FMoeXvcVZc3zO84ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
