apiVersion: v1
kind: Secret
metadata:
    name: restic-config-radicale
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:zoh9EDYb5xI1Z2ID9NexB07qoYKXJMAov7oBDBGdHYpTkxqHgXYVslfRvGx5O2O8qUSfJt/BAnv5jYhT,iv:WlTp5ERdsylBlsb4oFq+RpFpofqvcx4bFR/w0Xhpvg4=,tag:6AsZrV/UZb6h8XULPyEU/g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:lqbwUpyiSmq/rkIFlrfk8kwd92CW1Eo0bw==,iv:fuHZqhwTPUjvdd0pQRtizypFs94m/BnQbzhUq2F+h6c=,tag:YkPT3h3t5NxJ/OWt82gp4A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:pCY4680RT5O1F91bor1R54fb9lM=,iv:b0XKRH+A/nO7XRpnnp7gcDCe5qjlotHQNXzdaBXhJoc=,tag:X3PoOF/jyG5dT0v2ysw90Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:woZG8XvbuRPbvs1Z2FHrOsHpOrjCNtVeQETMX3e84OgBQ1wiVbhibw==,iv:IL9y/UqYOMnt7f0hlirfrb1WTilhAxruW/FSWMnOSDM=,tag:zKgJ8wiHHZ6G284m8qccEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabjRlSFhGcFdZdHFORTN4
            RmFrSWtVUlBoelR5RzZ3UzVuMm12TStCMDJBCnozQ3E5UUYyQVhFRXk2QXBvcWJM
            OWtLbkFZVUhMZ1ZWR1NCZUZQMTdha2MKLS0tIGRldlhwMXBIQUhnWUExd1E4cmFP
            TFFQbnM3aHp3aTR6bVpuVmhhYXdEeHMKl8kxtR9ejz2ej4eaXEbEJq5w17tIKGtK
            qPypiPQhV/zJ244rnJob+jofFeycR2dR3wQTna8TYF3UdD7rilNvdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T13:36:26Z"
    mac: ENC[AES256_GCM,data:bbm+D9KR8cplQ24L6nyyxb6ZDFENs/xc/rXpoRCa9x+2UNRlrYQ3knBYxBppQ9hDWBNJnGvwXXyz/xvQKYSwRJrEWHfDWMWMP5OEsqRhmXBHghFfuNrBNBTm9LR2Da6uzFUO9TWYUJlrv8+8DuuC/Z1wNiC3T8X29IyhX8zdbtE=,iv:eD1asqn1jTUgGXqaxap6AIDNQbzqoPYCemijvFE8T0M=,tag:kyKKl81w9eJ918C0gO8NrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
