apiVersion: v1
kind: Secret
metadata:
    name: restic-config-radicale
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Vt6gKlQcAcNr+JvnxADNGINPyk9E0qNOzLWlw6EAM4zSOXhUaWAsGfLeEzFE2zoLhojG0Fl/IyIItDvCilFVxjM/IQ==,iv:F0OeA2Zgkofi4Lfo/HLyQNyCgB493jAVmHVLw/9rF8o=,tag:OenCY8Ed8BW3E30JjF4EqA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:lqbwUpyiSmq/rkIFlrfk8kwd92CW1Eo0bw==,iv:fuHZqhwTPUjvdd0pQRtizypFs94m/BnQbzhUq2F+h6c=,tag:YkPT3h3t5NxJ/OWt82gp4A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:hNwgMmnCiDJ5dmLBVi0qZVEAbR8=,iv:hXvlEbc+W/kSt1DtCKhbBsZNi7ttOFWxLRnqqxAMPL8=,tag:O7fQAkSYTlv1SKnRulvrqw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:X6oP6ZSwdmfd7kulnA7RwMGTQ0KLW+q4C2CBVsfdROok/Qn9LT5vQQ==,iv:BTmyAtDhQnXoLgx00dhT8c6BtZ/AaSkpHdHthI12KYk=,tag:E/VVDZmTsOSsgbpj0t9ROw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabjRlSFhGcFdZdHFORTN4
            RmFrSWtVUlBoelR5RzZ3UzVuMm12TStCMDJBCnozQ3E5UUYyQVhFRXk2QXBvcWJM
            OWtLbkFZVUhMZ1ZWR1NCZUZQMTdha2MKLS0tIGRldlhwMXBIQUhnWUExd1E4cmFP
            TFFQbnM3aHp3aTR6bVpuVmhhYXdEeHMKl8kxtR9ejz2ej4eaXEbEJq5w17tIKGtK
            qPypiPQhV/zJ244rnJob+jofFeycR2dR3wQTna8TYF3UdD7rilNvdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:38:39Z"
    mac: ENC[AES256_GCM,data:zUe8DkL5FdtNBG+r3WifsGgw5AtNj0OI/jn43IfLjF9eyHooGYpe9w9zVh83P6z9yvQaY0f2B3vAsEkhzSW4GMN4yPvmju1KXmFwocyx7KEB8ReQrg5MHAH9P/u2hsGQgJ7Bx91QWxOIVKMqqx5gSfvmlGVY78J5tY+gVURIBxs=,iv:0ZuA1mYI/GzW+jd6QUdmLzWv31VASXTrUPa6RlSt7Wg=,tag:24AIvWHCWLSBLKYL8v3zVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
