apiVersion: v1
kind: Secret
metadata:
    name: restic-config-sftpgo-config
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Xf2BlyaDR9ZzGF+VU7EuEXcntE+mdbUxe67Ebw0PBev3keXS3MYYVlJK6pDjB+RJMIk9U/DgHDHxPpNy6+PrdeX2kw==,iv:uPk2K65ho1FELKGN2AZsqnTZse1gG9aBY/HO0CFXtYs=,tag:fWEEzsWuRWBu7SeNrtoyUw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:AHj7rKUiLV8T8gLfHb82Pq7smQUyqWBMOg==,iv:Ym6PlsRIUM283cfpyxrnu6LOGtPXR2LhR9JAtlxPFDk=,tag:+pj8wnsmctbLnl6milkMuw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Iq7ChlwpBC+A9M9z+WpS7UyUB6Y=,iv:OMdVTmh0fqJCWfloP9chyfOrwIVRTh54E4QM11l9HPk=,tag:8njnK/Dod7VGwod073dSRQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:oFgCc/Fu1YUnqLpbyvXPA9kPuvTxMWBQStC0Ec0wnb0DGt1W2qNJ7Q==,iv:jw8Qy3Gymc6I5J85XT4p75E/gkqjqWFSYw9vLkFTXR4=,tag:+BOxro4kaY8tX4sYFXqvIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTENGdXVMV1psRUJpSFlC
            Wm1EdUZtVExkOU02RzUvODJpWVBpZmlGQVE4CnlRQ2ZwemxrVlpYcU8wRmtKMU41
            VVgvRmEraGxZWFB0TklDL3hFYVhiQWsKLS0tIEkvK1F1V0ozeU1NWHF2cjlWbmxz
            djZJaGJSRHB4UVZFaGpodTU0Z1NJSmMKScjWzRO8+1UHSYTWLE9KAFvdvytvq4OP
            XA8XWTRJtuxus00pP5zoyePINclIIxGnjafp9SxY6+tBtKAxV2XStA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:39:17Z"
    mac: ENC[AES256_GCM,data:RCZykpYPf4/bLvt4nzA+lA9u8MRqztKwLIvXdxZMGeVCBENRen63W8RmmY7HhVd2uDZWP3BK3kR2JmVPPOsitUCTVeGgaHspsxCCW1RR6Wj6v5f19c8meCFSM0Nbk3FmyBsWc0dS4/PXBNYRO8YwQS2KYKpU6ZDiA+o4iTFEJyk=,iv:GV8SnVEin/C/EnE07QzWxO0nJp3tj/NH69oHgfcykC4=,tag:imQFzBm/XpgK9Zb6OBF54w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
