apiVersion: v1
kind: Secret
metadata:
    name: restic-config-sftpgo-config
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:TErgVaOhdpCcMZVHHbcQkzJA1huvIpNNIKdNYDmnoG3cvlsEi63Gsd+BD2wk02ryJjx4DBNMIsatwg6JsCEv1Eg=,iv:XOQ60FcsgYUA7tzds87SYKW1xz0h9DSu9LMQmhi50sk=,tag:4/7vv8iFxg7GzvUMJ79GmA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:AHj7rKUiLV8T8gLfHb82Pq7smQUyqWBMOg==,iv:Ym6PlsRIUM283cfpyxrnu6LOGtPXR2LhR9JAtlxPFDk=,tag:+pj8wnsmctbLnl6milkMuw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:yBZRkQgPKv0kduQnhe9K091UnaI=,iv:QeTGWuVeCZnejH76jz2ehr58IGvCV3+rbZ6eHl0g5Xg=,tag:fi4BP/eldgKsum4LCTgTHQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dLnSehUml2NtdR1HD0Lglee7XurJiy9LXqSfaTAYrH0RWuxGsJFNkA==,iv:0Y7mb2snO1culejJzWVNEAYLinaz5CCNZCD9ZCeWHfg=,tag:lpBcVsmMSXlmNwcnTPHUWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTENGdXVMV1psRUJpSFlC
            Wm1EdUZtVExkOU02RzUvODJpWVBpZmlGQVE4CnlRQ2ZwemxrVlpYcU8wRmtKMU41
            VVgvRmEraGxZWFB0TklDL3hFYVhiQWsKLS0tIEkvK1F1V0ozeU1NWHF2cjlWbmxz
            djZJaGJSRHB4UVZFaGpodTU0Z1NJSmMKScjWzRO8+1UHSYTWLE9KAFvdvytvq4OP
            XA8XWTRJtuxus00pP5zoyePINclIIxGnjafp9SxY6+tBtKAxV2XStA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T13:15:40Z"
    mac: ENC[AES256_GCM,data:7ASBHmp6eM97V6RwyP/ONA9+ZQVxwdDlab6osHioDEiXQ1l0LvIippxGLaIeZauEQr+Ts/EkwzSwBYaVrGWuxAYcB5Em/X+YAjeKuXMMWV3M9GBDSaRNxY+p7uXFlmN0bNeZUD2DScHGrrjGdVTPTYfnZqw4PgjxlWrxm/xIT1E=,iv:V/j4OTg3zigtroiSvxocK+KdUM4UZ1MDKLzSNhPtXs4=,tag:6xZ7MWee88tAC1oxn0wAqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-sftpgo-config2
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:TErgVaOhdpCcMZVHHbcQkzJA1huvIpNNIKdNYDmnoG3cvlsEi63Gsd+BD2wk02ryJjx4DBNMIsatwg6JsCEv1Eg=,iv:XOQ60FcsgYUA7tzds87SYKW1xz0h9DSu9LMQmhi50sk=,tag:4/7vv8iFxg7GzvUMJ79GmA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:AHj7rKUiLV8T8gLfHb82Pq7smQUyqWBMOg==,iv:Ym6PlsRIUM283cfpyxrnu6LOGtPXR2LhR9JAtlxPFDk=,tag:+pj8wnsmctbLnl6milkMuw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:yBZRkQgPKv0kduQnhe9K091UnaI=,iv:QeTGWuVeCZnejH76jz2ehr58IGvCV3+rbZ6eHl0g5Xg=,tag:fi4BP/eldgKsum4LCTgTHQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dLnSehUml2NtdR1HD0Lglee7XurJiy9LXqSfaTAYrH0RWuxGsJFNkA==,iv:0Y7mb2snO1culejJzWVNEAYLinaz5CCNZCD9ZCeWHfg=,tag:lpBcVsmMSXlmNwcnTPHUWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTENGdXVMV1psRUJpSFlC
            Wm1EdUZtVExkOU02RzUvODJpWVBpZmlGQVE4CnlRQ2ZwemxrVlpYcU8wRmtKMU41
            VVgvRmEraGxZWFB0TklDL3hFYVhiQWsKLS0tIEkvK1F1V0ozeU1NWHF2cjlWbmxz
            djZJaGJSRHB4UVZFaGpodTU0Z1NJSmMKScjWzRO8+1UHSYTWLE9KAFvdvytvq4OP
            XA8XWTRJtuxus00pP5zoyePINclIIxGnjafp9SxY6+tBtKAxV2XStA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T13:15:40Z"
    mac: ENC[AES256_GCM,data:7ASBHmp6eM97V6RwyP/ONA9+ZQVxwdDlab6osHioDEiXQ1l0LvIippxGLaIeZauEQr+Ts/EkwzSwBYaVrGWuxAYcB5Em/X+YAjeKuXMMWV3M9GBDSaRNxY+p7uXFlmN0bNeZUD2DScHGrrjGdVTPTYfnZqw4PgjxlWrxm/xIT1E=,iv:V/j4OTg3zigtroiSvxocK+KdUM4UZ1MDKLzSNhPtXs4=,tag:6xZ7MWee88tAC1oxn0wAqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
