---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  username: Flux
  channel: flux
  secretRef:
    name: discord-webhook-secret
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: home-cluster
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    # - kind: Kustomization
    #   name: '*'
  suspend: false
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: helmreleases
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      namespace: 'cert-manager'
      name: '*'
    - kind: HelmRelease
      namespace: 'longhorn-system'
      name: '*'
    - kind: HelmRelease
      namespace: 'metallb-system'
      name: '*'
    - kind: HelmRelease
      namespace: 'monitoring'
      name: '*'
    - kind: HelmRelease
      namespace: 'networking'
      name: '*'
    - kind: HelmRelease
      namespace: 'selfhosted'
      name: '*'
    - kind: HelmRelease
      namespace: 'cattle-system'
      name: '*'
    - kind: HelmRelease
      namespace: 'default'
      name: '*'
  suspend: false
