---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: jellyfin-config-backup
spec:
  sourcePVC: jellyfin-config
  trigger:
    schedule: "0 * * * *"
  restic:
    pruneIntervalDays: 7
    repository: restic-config-jellyfin-config
    retain:
      hourly: 4
      daily: 7
      weekly: 1
    copyMethod: Clone
    storageClassName: longhorn
    cacheStorageClassName: longhorn
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: jellyfin-config-backup
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-config-jellyfin-config
    copyMethod: Snapshot
    accessModes:
    - ReadWriteOnce
    capacity: 4Gi
    cleanupCachePVC: true
    cleanupTempPVC: true
    enableFileDeletion: true
    storageClassName: longhorn
    cacheStorageClassName: longhorn
