apiVersion: v1
kind: Secret
metadata:
    name: restic-config-jellyfin-config
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:jPL/WCUxNZw60igUYoZjrWq6gsPGEwMwJc9uz6gHnq6FYz7GctMR6VVtH/qv4E/8o+tCbpWmWO3uOEokv6mRYObh2gZw,iv:5gQC6TSQ02CvcLAG+5xopt+JeatDn2cS7k23QjFXO4g=,tag:/nv9PvznaPk/dtJZcUW+Uw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:hVJC5hLs6H8EoGukJFLdesZjhh81sGpv/w==,iv:AcNFoGbQ9QXRL/V+H63eKWg36s+oAYMsAFjyUu1iaxo=,tag:En7iqtT38Lo3cBFd/BXZ5Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5HzpK5UOS1FvDcqQtxvMg70fAxI=,iv:Nt4YL/EOP271JbVKTBe+FNC5nJTTh6sJxbGdldCkBmk=,tag:WOPYaw85CrQIp80a0UJQTA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:q9VZMX41K8JPi4o3HZ/nlHtQaHQCsuiJMVB2SsnQFkAUJXn5dQznNw==,iv:3qW7z6D0W2Sa2UVd/wSM+TREC5k+OBVIiTTUaRezAQU=,tag:zTMEwR2Quem59qp0JUVFKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOUg1RWR0dGo0enJ6eFpQ
            clBOdlg1U21QOUZGcy9oZlBXZVlibEQ2d3prCmtPUk9xNmE1RTRkUE80ZlZZNTVM
            aWUrelV5SUhXTXNXMjYzdUV1YTNqUGsKLS0tIFdoeUtlWkEyYWpWeDdlZXBMbHVq
            SXYwVmpKWVRTeXd4eGxmcmlqajZRWHcKJy9xQmNgMAKG2Wg2Tgv2bk4nbZldOPE9
            Pn8i5SeFRI9FUMvViRAE+tvleo6hvQLb7l20Gl/8KjiEET0VRjAWYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:36:29Z"
    mac: ENC[AES256_GCM,data:RZp3FyulWSi/tMmRIhMObBowlpCN6sawBP8eO6TguGj/kTZDAtxCGYvJcK9DIOFtZLQ+euI0vIelLO18tWRCiaKWkoDKZjuII8OyTjIPF0Yrct8YsixlNF4LO7Scbr/qG9ZyC1Nx7u9/6aVBdQaPB44uOoVFBlG1cBiWNV8LfCA=,iv:+w3JhGvarEKiY4FFuFuRZzkFvrwD1zEvqTi3/1TOT1s=,tag:pQlgWWWrwZCnJHuHoHI7Ow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
