apiVersion: v1
kind: Secret
metadata:
    name: restic-config-jellyfin-config
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:VY4Tsv07bcg8Ygii3ZgZlow/03sibIGe4UwAmZnNIXMsEwfKvXsGf4YJ/k1f9e4PuqtQFDRSd36Wrgq0IjGxz8Q+uQ==,iv:dHcAEAImvYSw8bop48LRFJvq3/9issyefglxkWQ/XN8=,tag:PhxG0XZhP8+GMLEnQSDw5A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:hVJC5hLs6H8EoGukJFLdesZjhh81sGpv/w==,iv:AcNFoGbQ9QXRL/V+H63eKWg36s+oAYMsAFjyUu1iaxo=,tag:En7iqtT38Lo3cBFd/BXZ5Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:1qhzZIYDFHvMduNaUzKCK4S6wwo=,iv:wWNcayRM8BtKPL6DaDRf7orLvqs+U+t3BLBi/9hxX9g=,tag:yC2HxqFuJrxlerk3qqsoFA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Gj9VGdb8Axqc3bv/P4wvM6z+RSfJsqTTcJ/JXFvcKd2hY2YPf8prfg==,iv:Jm52vd+gRVu1GwVXi35exzw/CMfEsT3Y6KtXI4e5jp8=,tag:bf/h4JUW4p0hz4vt6pwnrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOUg1RWR0dGo0enJ6eFpQ
            clBOdlg1U21QOUZGcy9oZlBXZVlibEQ2d3prCmtPUk9xNmE1RTRkUE80ZlZZNTVM
            aWUrelV5SUhXTXNXMjYzdUV1YTNqUGsKLS0tIFdoeUtlWkEyYWpWeDdlZXBMbHVq
            SXYwVmpKWVRTeXd4eGxmcmlqajZRWHcKJy9xQmNgMAKG2Wg2Tgv2bk4nbZldOPE9
            Pn8i5SeFRI9FUMvViRAE+tvleo6hvQLb7l20Gl/8KjiEET0VRjAWYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T13:28:47Z"
    mac: ENC[AES256_GCM,data:Vqw/wDePdxJTDNCa+/nAcVovROcM/eRnh7SvW0ItFkLaPwarjvPehQjXiMK2kzuJ7Ago32+9dxd6MTKjM+YcWXvw9MF0jtkc11cjyyeSImGwdTJ8wry0yQOSdAXM7EhbmCndjaYqcIXFhBBA0L0wXhi5h87VfvyhWjg0gkqzKs0=,iv:eNKPUqb5Tvh6OusUW4lAnjeYxeZ8mE9dhuO8xntI12k=,tag:N/MY/1oEINqUrKmJsmNPsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
