apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pvc-postgresql.yaml
- pvc-redis.yaml
- secret-authelia-users.sops.yaml
- secret-authelia.sops.yaml
- hr-postgresql.yaml
- hr-redis.yaml
- hr-authelia.yaml
