apiVersion: v1
kind: Secret
metadata:
    name: restic-config-authelia-postgresql-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:AayraEYa/wlfh7awk39wwzegJ82/CLc3pot0DHglwmCZ/mnjB4y8PGWPT3OtVoULRvsQcAsswFn62C5HsxONxtQrae1cVvdPmvVXTjm6,iv:Qz2290UYaFxyfGoLKx+axlDR6uO75U5mn2pp1z5+Zms=,tag:0SqZp86XTnG6Lg2qdmGgfA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:VBA3ZhyG1krIVe7NET/Ntp/zHcHwIi6wUA==,iv:HF4jpKHnfCvsplpKPzmnXLzVEOzNpCkt8U0Bqd8kMa8=,tag:n3Zm9jv0Uex6ZMsdlKMlxQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3xdsNWK9K3D9+TdTc4ioNSwAC54=,iv:LkurZex39jRRckYrDgESNzuJZNwVjBaTDzlvJL0UE/c=,tag:OsuggSJEnZfVMSZkaNb7nQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QvI9qplQoeEtqzAljK60PwbjwTYxaFcGyO+i0F9DQojik2E9XmHsyw==,iv:4DAssa3GFGtWj4Sly4jQMiwAYDwJqlr8YGmbHEKwF+A=,tag:f3vbywms91G8VRSZua7X9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVEZzUDJQNXd1NSsxU2l5
            U0tDaXpGcDhGVHVSdjhDNmdBSkk5WlkyS253CjV0bk8vWEk1R3dRTDEzVWRucXJO
            ME9jYUVYSUpNZUhkekgxT3ZNZ2NHSGcKLS0tIEVLMGczNGh5LzhsQTNIL1M1bVdE
            YTlNYUNQSXo3REpLUHV6eGlEeVkzNlUKXOYJhra9FzFn02Po7YakUEjPDS++nHvP
            yaE/fya721BMifrqcUCfWHzzxShcePFmvr+dUUKQlYJ7Nyuob5QuAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:35:19Z"
    mac: ENC[AES256_GCM,data:NJWV5ojNVxaX3b4oLgylIDJ6j87xqiniyVwv3jp2b4UTz3LDGG8GmnuIJQfSp4Xr6Fl5njkbJWIHSPLV1NeHNzgPy9+tg803vcoOlC7vdha5ulqDqqyoYaJn63JgNRvLSGUtb/JnNUly6qSBzAUq3FSiJ4LZ28vZCoihTOeia7Y=,iv:dN+TmSFXe08LaYqOV+rcuC0qtaBCs0AME2hfDfhGiUQ=,tag:g3US4l49AEVoNAn/upREMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
