apiVersion: v1
kind: Secret
metadata:
    name: restic-config
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:9JpBLI8paZNbuXowjY7OxJrbAR2oSOn8n7d0gMw+6KDIb7vTL7ZVkuP89opiakasWXeaHNCEaVt93GbhwsKya6Lxn+HUHN0HJRNwsQ==,iv:wl1tVzP7O2CjATsjdoEyD92ZgFLlM/PIwddyemgIYf4=,tag:MI4+pfqLkbnZCRqwPXRQ8w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:VBA3ZhyG1krIVe7NET/Ntp/zHcHwIi6wUA==,iv:HF4jpKHnfCvsplpKPzmnXLzVEOzNpCkt8U0Bqd8kMa8=,tag:n3Zm9jv0Uex6ZMsdlKMlxQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:393IhpPCnPfgS5fZCRJ9Aimal2o=,iv:mG+MJJqrhxK5aVZg71RJ7rN+tlpA0GZiMjg5MDx8zFo=,tag:fkhVNGSU5t/pOKs9sRiSuQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QjBzsjMXHrioCOWZBVS8AhpgZvDyp0jFdhqOAV/1I3OkPdFPiHtsCg==,iv:sYWv9YQ9QxZzHiXuN+cTycJqur9hoSCi6fEI4Yn4FL4=,tag:y8dxFFqIebMEHe9FlLnrtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVEZzUDJQNXd1NSsxU2l5
            U0tDaXpGcDhGVHVSdjhDNmdBSkk5WlkyS253CjV0bk8vWEk1R3dRTDEzVWRucXJO
            ME9jYUVYSUpNZUhkekgxT3ZNZ2NHSGcKLS0tIEVLMGczNGh5LzhsQTNIL1M1bVdE
            YTlNYUNQSXo3REpLUHV6eGlEeVkzNlUKXOYJhra9FzFn02Po7YakUEjPDS++nHvP
            yaE/fya721BMifrqcUCfWHzzxShcePFmvr+dUUKQlYJ7Nyuob5QuAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T16:40:55Z"
    mac: ENC[AES256_GCM,data:N3KymqWsf6l6+CbrabcaZP7FZlz2S2FH5syLRIi9xgratvuOgiiZPvAdAVdTLbsCcZUVKt6iEnOmihYCQD9gvGjfNrHpLS6Yw4bF4IXeuQfw0eFdXpW896BCmB7iDvx6O92xeQLdvd+Io9wNmBgj2oReks1PbeaQWIWrNTRtzqw=,iv:TMkbC1+LM9R8fRdtYL0IXbBnJwJ/bhy99EALpMiV0Jw=,tag:ctpAnChBIMrXf2wAdYIpoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
