apiVersion: v1
kind: Secret
metadata:
    name: restic-config-memos-postgresql
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:jISD36/gMCrbwj30I5dw3dQwmjpGATVV/SF9q/9b5r88ivv/dAkL/u/acj6GEhFLafIXcJpfqoOSCZwFUMjFioAqkAfzFau7ZhDP,iv:Qyq2vdTyfuJugdE5fIbbKcY8ctxHMSibadYy6AJWmwc=,tag:PviGFfnuonPgKuM/IplyAA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:JTzDw2h4lAL5T2TA4yxh6ySTXQdrDmUWmg==,iv:dewUd4DLeCxSRYPHGR4KUcrZfCrZc271IDfAnH5hPts=,tag:fWUQEV1ikyzYQ8S7OIYzvg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:dFjZrJj7PwaUfR+pSnJwKbzepGI=,iv:CI0IZM4nkcXvRSey04Lqhl0fLSRaxvjEN6ai9Sa1UdI=,tag:ngkLDFsjRtf+LMU8WYctcw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:nh2U8lUvYEaAbh6mfAqP9DRS/YVT+3KN2pXp8efB3GSAGN6RCLF+IQ==,iv:aC+WQ/bWeuiAiweEK+5DZiPRxEm1E79dOq2lGldwb10=,tag:2dc0Ai+bQq/+Ng3zmV3PoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVEw0cG1xTUpkVHo4eU5y
            OUp3M2dCU1FHOE5yVlNMdExWUGVLQjBsSDFVCnJYQ2swSDBuTWJwdnBHTUg4VjY4
            TkNXYVQwMGtGWDlUUGd6YS9Lc0RtNFEKLS0tIHJCMDJ5Qm42dmxXRi9BOUxYc0Vu
            ZGhMRU41ZFVPV2VDNnlCWHhWb2RSRFUK1TO146rH6397zhye0yxV9INDjM9WXam6
            +kxhVlHD5V4/A6EaPrOSgSea5x3LhB5u+NYZBWY2FT0mGWaMmRyXnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:37:57Z"
    mac: ENC[AES256_GCM,data:BMoe3elHiQrCcM4XNWZZRY7nmzdwhsEPnxNUOfWlmoZzXyTya0zpEOBIQ8Oau8e9Z12+wHYYRprDC0UxSmd08tV6dn7f1hRn98kJeOkFJOuRUyzY6sohsOkLXJp9wjxEx1W6jXuJpgH1fJo1wGckW8oL4IJW8KPu00QZzlapcEs=,iv:dg4ePWNajFp6kZhrLsTbP4FmZLHz33x+hyr9B01cNPc=,tag:x3jBAmmtVqM9kccH7E8KSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
