apiVersion: v1
kind: Secret
metadata:
    name: restic-config-memos-postgresql
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:OYdVaW3lIalEIyCOrrCTxKmMNRLqd1N+HVQC/BD6lFsbiVUM5E6giR0Y+adlj/6D5pLZeGfryTgfS4DFlLZ3FOxx3lI=,iv:lrFh5x4MBdS+PuXl4j5x2pciHE4x4i+g9w3s7jcjlKE=,tag:jzBfuMSXV3vz5MEIQQv/+Q==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:JTzDw2h4lAL5T2TA4yxh6ySTXQdrDmUWmg==,iv:dewUd4DLeCxSRYPHGR4KUcrZfCrZc271IDfAnH5hPts=,tag:fWUQEV1ikyzYQ8S7OIYzvg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:II07Vb2MJc4Y3/qqGpqZDlcl6UI=,iv:N7fNO59E+JfTkvJ33t/aORUgboWYvr5BLIgLcag2S4E=,tag:k9xW3d8MCgk/j8JX4VfjdQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DaBh2sG0BpgI59l1XRyqmHn3znYkyVnBk3dTAPCtrV/auWDsNKax/g==,iv:DUGD/tx1K2kRrF+AoY4BQf2+BQTeL5t0BOz6EAJGj7g=,tag:vjgTqaLQbxWuZObgJ5ma+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVEw0cG1xTUpkVHo4eU5y
            OUp3M2dCU1FHOE5yVlNMdExWUGVLQjBsSDFVCnJYQ2swSDBuTWJwdnBHTUg4VjY4
            TkNXYVQwMGtGWDlUUGd6YS9Lc0RtNFEKLS0tIHJCMDJ5Qm42dmxXRi9BOUxYc0Vu
            ZGhMRU41ZFVPV2VDNnlCWHhWb2RSRFUK1TO146rH6397zhye0yxV9INDjM9WXam6
            +kxhVlHD5V4/A6EaPrOSgSea5x3LhB5u+NYZBWY2FT0mGWaMmRyXnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T13:33:52Z"
    mac: ENC[AES256_GCM,data:xXRgc5h0R9fRTIX8+0afe2mxnDkz2y5kZLE58r6IAfoTTB1cmYNuv2DwbnanStRl4t4/sPHT9UyZuksp/JYG02AIyK2Nxrq8voPaRe0BbTKqM2E5xaq8SovEnHi/xAhzvw9T2TJs4BFMX8UHnTZc7xlFKwQ0M3Bz36bCMWMIx40=,iv:Kia56gWgtIRI0kRNxBjgs457X+Y39A2ZzKhZMxgtQAc=,tag:xT4Ockob4j5/OrINqxtoIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
