---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  LB_IP_NGINX_INGRESS: 192.168.100.211
  LB_IP_NGINX_INGRESS_EXTERNAL: 192.168.100.210
  LB_IP_SYNCTHING_SVC: 192.168.100.212
  LB_IP_SFTPGO_SVC: 192.168.100.213
  LB_IP_BIND_SVC: 192.168.1.230
  LB_IP_BLOCKY_SVC: 192.168.1.231
  KUBEVIP_ADDRESS: 192.168.100.200
  CLUSTER_BIND9_ROLE: master
