apiVersion: v1
kind: Secret
metadata:
    name: restic-config-immich-postgresql-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:2wYSZsWXT5iowzz8iEmgJYeelrhQqIMTpy+m1peg9myzITuKr0uyQFmdkP9wdmVxO0ApoXSRvr4YA0kVd7sKbMene7Rei68cz4VX1Q==,iv:ocecgAqPNcXIPrdAiqygIWk2VGddiVP1FiVr0Md/Plg=,tag:QiapYKKl5Uwj2Cqe3wTXuQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:gBeckSc+QeiWh3so5LbtXDSGcbyXftDzzA==,iv:f64PWdTdW0merkinyVvDfrPhtHXDULPw/P4o2glHpHI=,tag:i8/kDVqdJSPUMTuB4oy7vw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:LS63Fijknxv01BQAZQ4kAaRWotc=,iv:+4DbtY+L+nHo6GmMPWxklaqd7d0hMFlfMYm1vAHjUUA=,tag:iYhSaLtmkTbm0La2QyS9zg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:c4dzOpPyhW/J9rc6zzxp4tyqsSvVxDBvT9FGre7nyFcZpFeFYc5Skg==,iv:4PMERyEc0yu8LHfhTTKXe1u+NCH32qmy0JIIoLRqGiQ=,tag:1Qze014yg0+T1kXIVsZfqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeExhbjBUaUJYVmRFenA0
            ZitGN2VMWjN3cERESDlEdHFjWUVFZWNJZjNnCkFnaml2SFYxMlZxZFVRZ2hyZzFK
            Z2VPVEpVYmxNMUw0a1FrRHlSQTZvcmMKLS0tIGFHOEMwWXdRckFmcThhVXJFZ2x2
            YThwRlRNcEZGZVUyZ09XZk5jVzVsQWsKmHOKxvWVqSTQyJrj7PIG0zRBKpqfEpLn
            Q0XdPh+4aDcC6E5PRaRt8yP72QC7kNUtskia8uQrtMiXU0LFmvmIug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T15:12:40Z"
    mac: ENC[AES256_GCM,data:LXhI5MJVMO25f/2VVEbcOTywn1xQDAGSdsGZdqed5++cWUVd5hieTJjM+WLVYZLlkkziGzwS1dbPnJB+x7GulVBgO0liOIWOCmPI/53NcGtArbQsIPG+mgmQG6TYOcO22gTic0CaG+K4fZ7W2/LDY15C3/cJyNwb0RfjQceqTTk=,iv:5CyKODFmPnsVpsZ4G2Xh2TLY3P9iq0oUZpZiIj6Q/sQ=,tag:hQwiX1Cedw/ohCcKzVJhQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-immich-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:sqdhT/07g03fKaAk1ffJB7njxxAb88ZxXC9HbcxCOQ3fqxmtTm/SX5uDhmGtRyDpB1JtmLey6CHrCKANNWbk,iv:lqikCbEO2EApupK7T9toM/lX03n4L+7UeQpHr9kp/kA=,tag:dP0YvkpObOKj3PSQ6m96kQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:gBeckSc+QeiWh3so5LbtXDSGcbyXftDzzA==,iv:f64PWdTdW0merkinyVvDfrPhtHXDULPw/P4o2glHpHI=,tag:i8/kDVqdJSPUMTuB4oy7vw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:dvlw5hNRlDiKO72BS/mJRD25Qv0=,iv:fUXCZL0043FL3v/dBXXqtMwBE3K4SdwGKOXwndiKP3I=,tag:ZhuhIZ+4Bj4wgU1TuFB4xg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ebGt6B2wY0wvQBgA90j1cYxBtwg2Ug+S9UaFnL1beIj7gRnh2HJbtA==,iv:82JjFjPtlNg26MyB9mOs3pArPT5TfNsZ3HRh5MgXeqY=,tag:v+ZbtQE7ygMG+87aH8q4cg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeExhbjBUaUJYVmRFenA0
            ZitGN2VMWjN3cERESDlEdHFjWUVFZWNJZjNnCkFnaml2SFYxMlZxZFVRZ2hyZzFK
            Z2VPVEpVYmxNMUw0a1FrRHlSQTZvcmMKLS0tIGFHOEMwWXdRckFmcThhVXJFZ2x2
            YThwRlRNcEZGZVUyZ09XZk5jVzVsQWsKmHOKxvWVqSTQyJrj7PIG0zRBKpqfEpLn
            Q0XdPh+4aDcC6E5PRaRt8yP72QC7kNUtskia8uQrtMiXU0LFmvmIug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T15:12:40Z"
    mac: ENC[AES256_GCM,data:LXhI5MJVMO25f/2VVEbcOTywn1xQDAGSdsGZdqed5++cWUVd5hieTJjM+WLVYZLlkkziGzwS1dbPnJB+x7GulVBgO0liOIWOCmPI/53NcGtArbQsIPG+mgmQG6TYOcO22gTic0CaG+K4fZ7W2/LDY15C3/cJyNwb0RfjQceqTTk=,iv:5CyKODFmPnsVpsZ4G2Xh2TLY3P9iq0oUZpZiIj6Q/sQ=,tag:hQwiX1Cedw/ohCcKzVJhQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
