apiVersion: v1
kind: Secret
metadata:
    name: restic-config-immich-postgresql-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:nuqQHxnETXFoSxu4iCSmALGFYuQGnp71xBkdW+XOQYEecVLc7zDtf0vLg0i6henenrDMhjR/Pmd3ECl0ds3BGxpDbs6I0/bwVsg=,iv:rLFIjheMonwgbqMvPMDhP9xlApwBy58d/UqVC9aK1Cg=,tag:FWgOd238Dem9FPx2y3ntIA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:gBeckSc+QeiWh3so5LbtXDSGcbyXftDzzA==,iv:f64PWdTdW0merkinyVvDfrPhtHXDULPw/P4o2glHpHI=,tag:i8/kDVqdJSPUMTuB4oy7vw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:dvlw5hNRlDiKO72BS/mJRD25Qv0=,iv:fUXCZL0043FL3v/dBXXqtMwBE3K4SdwGKOXwndiKP3I=,tag:ZhuhIZ+4Bj4wgU1TuFB4xg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ebGt6B2wY0wvQBgA90j1cYxBtwg2Ug+S9UaFnL1beIj7gRnh2HJbtA==,iv:82JjFjPtlNg26MyB9mOs3pArPT5TfNsZ3HRh5MgXeqY=,tag:v+ZbtQE7ygMG+87aH8q4cg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeExhbjBUaUJYVmRFenA0
            ZitGN2VMWjN3cERESDlEdHFjWUVFZWNJZjNnCkFnaml2SFYxMlZxZFVRZ2hyZzFK
            Z2VPVEpVYmxNMUw0a1FrRHlSQTZvcmMKLS0tIGFHOEMwWXdRckFmcThhVXJFZ2x2
            YThwRlRNcEZGZVUyZ09XZk5jVzVsQWsKmHOKxvWVqSTQyJrj7PIG0zRBKpqfEpLn
            Q0XdPh+4aDcC6E5PRaRt8yP72QC7kNUtskia8uQrtMiXU0LFmvmIug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T13:27:13Z"
    mac: ENC[AES256_GCM,data:Nzkh4L/gu2s2PTKjEPy7YpZk7ASSbvHsvISo/nzffh/hG/liDbZK5kfqRMJLNtIrTao12oypLbFZ2z/y89nbixR4SVm6eSolxQY9g8OcWvxDlhtJC7kDAAcOVG2kBAAyLDN16774CdzbnwjK+0POzoJjq+LUktfVya7mkMCnx0s=,iv:ZsvpbIEJDi6hlcPkezRVh1YRWs44+YtNoC8lg+kyeBA=,tag:dtOs+8hnYkiaCCRs0gq/Ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
