apiVersion: v1
kind: Secret
metadata:
    name: restic-config-tandoor-recipes-static
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:pUu338JaYszyvuxdXbxkae5C/02n6lBWXvjEXormc43Lfp/LaXO2GUS9Aot7vnk2ZzYHwBcPp5W8+wNSLi0+Gy1rXjpfYRMYHoM=,iv:m4LSDRYr+Pb39x9bLw2EvTjD/MjQARAjeR6ok2ZaVws=,tag:KZkV80Ir5rpZqYtiR2kHHw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:GyxvqZeSkC9ibUwlxj+xAhvS64AyzAILLQ==,iv:gI1PSZzyQ2QTH9WFvwsVcqNvL0vAGC9DV1+8KXtOvuU=,tag:q8/cXYPHLnsqNlyAHQ/QbA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3SwV3gFU2rAUOvx23VPa9kM+TZ0=,iv:W8AknzsqRp7kP1IQv0Od8/dkBmyUWOeDZeG3Aa/9Udc=,tag:O/wEfa2JsKksUymzSlpa1g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Xs5n3ECv1noBnRY6//xuf/G3HGtlrQ6gv/eMRZd0dYaBLU/4UVqKBg==,iv:8jyIB03lN9kTUxBBv6zvauRxov39x6Vx965GeScJK+Y=,tag:cdwzOleMW5759OJfW37+LA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheXhVbXVEL0ZCV3laaTBi
            Nnp0M01hVFAzOEY3MDFEZzZvRDdLRHJmQWtnCkZNSnNNeHlxWlpHTHVMbWdmR2hq
            QTZLbHJrU3AvNmgzaHplcjg5bmJYZncKLS0tIG5KTkpTSjlYeGo4dlVRVFhPNjA3
            NzA4ZTBUQWNiRWFxY3lxRmQveW85dVEK89/hYR1WuXnY+4w422yC3rDpMDZWJYKb
            upSymAPSr8mbDaNxwtMGURfGzm88sdWqxHVBjA5NIP8LkiooCDmz9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:40:32Z"
    mac: ENC[AES256_GCM,data:CRG4wqGiySB1f6WX0zLIjqYfVvcGBVunvOiDS4CcIrn8xWRHVv7HnKF7rsTyY1uPk7xlT9M5+dLofsWzMXkPG+nNln8T0ovBw2D08PV7hMNSqJoYNfv/Gm8CZFF8FAJyGloDlH1cDe9bZ1voybpc+4h49Fe4Ipte3j8f0Jk2dK8=,iv:vieR8Y/X7U6ARTKBO26o1fJ4BpKCm9P265tl/MkfRK4=,tag:Zep8w4IUCMZmH7TG5+2rLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-tandoor-recipes-postgresql
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:vuINv+Vo9F5bS37UCf/41gNItwJQNt9/dWgEhuFiUxNY1vxof2+int+mrYUvgeQmGhzqE7uorIIWG7Tf9Gdf+pA04Vg+lmnnPxbk2gu0kg5uI88ilg==,iv:6IYAHbEndu39tOVNBKk4s186BA/6yu+pHqJHntlz2i0=,tag:Cc3W2FoN+wZAio6WaaNy7g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:GyxvqZeSkC9ibUwlxj+xAhvS64AyzAILLQ==,iv:gI1PSZzyQ2QTH9WFvwsVcqNvL0vAGC9DV1+8KXtOvuU=,tag:q8/cXYPHLnsqNlyAHQ/QbA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3SwV3gFU2rAUOvx23VPa9kM+TZ0=,iv:W8AknzsqRp7kP1IQv0Od8/dkBmyUWOeDZeG3Aa/9Udc=,tag:O/wEfa2JsKksUymzSlpa1g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Xs5n3ECv1noBnRY6//xuf/G3HGtlrQ6gv/eMRZd0dYaBLU/4UVqKBg==,iv:8jyIB03lN9kTUxBBv6zvauRxov39x6Vx965GeScJK+Y=,tag:cdwzOleMW5759OJfW37+LA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheXhVbXVEL0ZCV3laaTBi
            Nnp0M01hVFAzOEY3MDFEZzZvRDdLRHJmQWtnCkZNSnNNeHlxWlpHTHVMbWdmR2hq
            QTZLbHJrU3AvNmgzaHplcjg5bmJYZncKLS0tIG5KTkpTSjlYeGo4dlVRVFhPNjA3
            NzA4ZTBUQWNiRWFxY3lxRmQveW85dVEK89/hYR1WuXnY+4w422yC3rDpMDZWJYKb
            upSymAPSr8mbDaNxwtMGURfGzm88sdWqxHVBjA5NIP8LkiooCDmz9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:40:32Z"
    mac: ENC[AES256_GCM,data:CRG4wqGiySB1f6WX0zLIjqYfVvcGBVunvOiDS4CcIrn8xWRHVv7HnKF7rsTyY1uPk7xlT9M5+dLofsWzMXkPG+nNln8T0ovBw2D08PV7hMNSqJoYNfv/Gm8CZFF8FAJyGloDlH1cDe9bZ1voybpc+4h49Fe4Ipte3j8f0Jk2dK8=,iv:vieR8Y/X7U6ARTKBO26o1fJ4BpKCm9P265tl/MkfRK4=,tag:Zep8w4IUCMZmH7TG5+2rLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
