---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: home-operations-charts
  namespace: flux-system
spec:
  type: oci
  interval: 30m
  url: oci://ghcr.io/home-operations/charts
  timeout: 2m
