---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/rancher/system-upgrade-controller?ref=v0.10.0
images:
- name: rancher/system-upgrade-controller
  newTag: v0.10.0
patchesStrategicMerge:
# Delete namespace resource
- |
  $patch: delete
  apiVersion: v1
  kind: Namespace
  metadata:
    name: system-upgrade
