---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # dataSourceRef:
  #   kind: ReplicationDestination
  #   apiGroup: volsync.backube
  #   name: qbittorrent-config-backup
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: qbittorrent-config-backup
spec:
  sourcePVC: qbittorrent-config
  trigger:
    schedule: "0 * * * *"
  restic:
    pruneIntervalDays: 7
    repository: restic-config-qbittorrent-config
    retain:
      hourly: 4
      daily: 7
      weekly: 1
    copyMethod: Clone
    storageClassName: longhorn-local
    cacheStorageClassName: longhorn-local
    moverPodLabels:
      setGateway: "false"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: qbittorrent-config-backup
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-config-qbittorrent-config
    copyMethod: Snapshot
    accessModes:
    - ReadWriteOnce
    capacity: 1Gi
    cleanupCachePVC: true
    cleanupTempPVC: true
    enableFileDeletion: true
    storageClassName: longhorn-local
    cacheStorageClassName: longhorn-local
    moverPodLabels:
      setGateway: "false"
