apiVersion: v1
kind: Secret
metadata:
    name: restic-config-qbittorrent-config
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:kp3pMXjmkrJUdGYRSaUCZCyVJyHTfaybKPGSe6Bh7amK6zliaj8mPSwuIBhVcCYZJI2MP0Wke5L/BbwEgmBUS/tFQm25Pw==,iv:TljAicjNI5dzVeD2KaHVTbWgZcTW6EH1MrjHnLLZlG0=,tag:VBwbMR0j+KYAaC66Ux6R5g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:aCY0pcJGJ4/B0Uzj58a60V1GrdSRekWHHA==,iv:6Zw+DfH+zk8oApSFES1Sc33hrng4M2WCaH2bXpPCH2Y=,tag:3cBFQhoBedrCrMSbaIAqpg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wr8vEz926yizTYG8Td3WN/kAYrY=,iv:6rrqaTVDxGL698YtDL+HlzAvscErDl424KtksP11ce8=,tag:dk1Ixx+k2H7slqnh2m4EkA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ITKjk2C+hTsaaDwoT8/9Vtfgv7tAxgZmTwZO+TP/t6sBTURV5ziLpw==,iv:9vdTA42JGk77rpFWcNSrTjXgkt4iVGByZh/BxfAzNwE=,tag:05FgsbDjgIZSBt+/o3e//Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZ1dkQlNUdUtSY1AxSnBn
            QUE5eXNFTzUvTWdsL1Z4ZjBxYXVDcFBscG44ClpEbWFiYUdvQzRtYitKSHQ2MGV4
            enQ5WHZVbFhCTmFzS0tlQ1RnK2Q2T2sKLS0tIDFCQ0hKeDFUMEFWcWlPTmo5bWkz
            c2pEc2Q0VGNHR3QrNDhPQmx5ZEpIekUKNm3tLug19VKvPnsaNKfnQmy7Ig/S1tg8
            8deLVlt46n+P7Ge5jGyA1qoArpT5ImKlb6VUebybBVEOkJuyB579pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T13:35:40Z"
    mac: ENC[AES256_GCM,data:lTmORJRa+Uj/CAg3gsjhub1zG71ov1UWYZXRyWkhMQUL1hQV5MIBHxWIjeX7ePzEn0a4OyBwuug7MTY9bg1DPO+hd/X4KkMgbaEKwdAdxtNFpxctuTUBu5QFrTJv8QXobHvYdTwajrT2HOwjcbppNFBgTupkF28dRL4xMLD0cBM=,iv:XOYqxLSyheQmOJdQQ4OvMqhIM2i6eRmax7oPhk947Bc=,tag:GmMjwHqbGOmW/RDG/xuRgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
