apiVersion: v1
kind: Secret
metadata:
    name: restic-config-qbittorrent-config
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:K8Jkms4E/f3Dc0huO1w9GgLr4yuaFfcgSgKucnkk/TryGDXGygkrr5jmmh3Si+Th96Ya5mAQ7Jnb5kROXhcTCZ2U5Bjbe3bN,iv:bOcEPNgCcQeUw2n3J5bB/1p+2pYg3cdLH+r/JWVKPtY=,tag:Pk6l3uNX62dloIc/w83aCA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:aCY0pcJGJ4/B0Uzj58a60V1GrdSRekWHHA==,iv:6Zw+DfH+zk8oApSFES1Sc33hrng4M2WCaH2bXpPCH2Y=,tag:3cBFQhoBedrCrMSbaIAqpg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:HmX04u0Vd530ZSo0aKBvlpOoAaI=,iv:gwh3IAgdQOIJM2F4kDBYAbXaEukciNaaKBeu2aBEw2s=,tag:YGOyuWJvq2FbfxbyNO1Dig==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:G5AU2ZuqAKwH7llHz8tgGOX02Ot2EgtLKumQ9Joy433O9DTPJoj+1w==,iv:B8JbsRHKdMf/MLCTHFXT9O/p/rRQBBJFGBR0mMOTzOc=,tag:3eOD2EibUWFkbjOw02x8sA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZ1dkQlNUdUtSY1AxSnBn
            QUE5eXNFTzUvTWdsL1Z4ZjBxYXVDcFBscG44ClpEbWFiYUdvQzRtYitKSHQ2MGV4
            enQ5WHZVbFhCTmFzS0tlQ1RnK2Q2T2sKLS0tIDFCQ0hKeDFUMEFWcWlPTmo5bWkz
            c2pEc2Q0VGNHR3QrNDhPQmx5ZEpIekUKNm3tLug19VKvPnsaNKfnQmy7Ig/S1tg8
            8deLVlt46n+P7Ge5jGyA1qoArpT5ImKlb6VUebybBVEOkJuyB579pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:38:27Z"
    mac: ENC[AES256_GCM,data:mx12UjFz65DfnSzjdyGFgfa2KM9nfQE2BcQ8OcMaxkkYraG4wZRZZv3zYnCElu/ipoH/rnRECv8xRNRLwSD+DI56TMVsN5om5gAAXGbebr+5GMjK6pdfYk+9v5ga2hhq/7dQYUsS0kImft86hj6T9MgLa21xhNy5pKRQ+UQONhg=,iv:9/bihmmuBc6+dLttmeCJpTj6t91kvqxIXVkUpiFyt8w=,tag:7gU23CLC7tKXFUNgPYeIww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
