---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  LB_IP_NGINX_INGRESS: 192.168.100.221
  LB_IP_NGINX_INGRESS_EXTERNAL: 192.168.100.220
  LB_IP_SYNCTHING_SVC: 192.168.100.224
  LB_IP_SFTPGO_SVC: 192.168.100.225
  LB_IP_BIND_SVC: 192.168.1.222
  LB_IP_BLOCKY_SVC: 192.168.1.223
  KUBEVIP_ADDRESS: 192.168.100.240
  CLUSTER_BIND9_ROLE: slave
