apiVersion: v1
kind: Secret
metadata:
    name: restic-config-jellyseerr-config
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:NE4F/d07wBjg5UtBOP6gleoFMfXfyJmMmRb0wnCqD9N7WLVS31Thmuy0MEjdz+HoDSTwRAUlxaRTcuU5lpQEs6qqr9sGwE0=,iv:NNoHyZ4rWtTv2WD+Fkzfr3be8IoyiZw2YVQwZ0eMY9w=,tag:jz2CQpTcZ1fYr+NSJJpYXw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:uoGebIdkkYe8KoHFFxPpaj3ymaIvWK4QZg==,iv:oFrOcmmiQGVvKSs/EFqdo9WRdUgFZMIYM+DLv5614lU=,tag:IosqQWiKMIh/nV9IF1K4MA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:HOducR4qyCWls7Pf0x0gX4Gjnu0=,iv:COtjc0vHEheQuCdo8bTESYkwJ/f7eJMcpFXWL/5NQV4=,tag:Asc4zLZgfAfug/23Z18GnA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:coH9+QwyvbFKNo3OJucxKyaBAEpNhwqwK44Qr2XgUYppVJedDz7YKw==,iv:Mg9xK+YYfm2fWUcIAF/IK7ohQOPgL4LXsvnnc8rRyfs=,tag:oMlddwcaNGQxw0Tq+Q34jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MFZ2WVZkTTFBOEtxODZH
            MzFKT3JqWWhkajB1VWFLelRhdWxiY3FvWGhvCll1MERZMlVmdlY0eWhZcTFtUDZr
            WFE5L2RBdmJzeU4rNzR2WVg3c0hiNTAKLS0tIEdYUXFsNUtqQUVyR1EwNllQVHRT
            MWlPaFhMZEl1Mk8rN2NZV3IxQ1hUNnMK3tWR8Fw/GC45jHwtPZaS2Dgq0RiKiNGX
            G42qZua7otMy4PeMpCfOmoM/bVJXhKN1sgt/aFjBhwZWIOf2XrtpnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:36:51Z"
    mac: ENC[AES256_GCM,data:Gp1m2AInQhXR+D0mMep8sUJGEXZfBGOr6INdoPnnADATq1KBA8E9OpqyUknMBMPBF266Xbaz5yHRr4mJGOeF4mTUVBtIf5f+WiFKAQdywbAScrQNDjenIcnQDzV7wK3U9GMoXTZjCFYMg4634UC8Ge1do9DC6GQ5DRzExmtXmRM=,iv:raMM1brp3DB4zdN6H+8M7ykNpw3lFp2RZrs3M6L4IL4=,tag:wnVUwktERNRnfrSSOeCKZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
