apiVersion: v1
kind: Secret
metadata:
    name: restic-config-jellyseerr-config
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:EA0rX/7+Mtg2VPb5S1n8hywp9JTWIJ3LPjF5eSFMTz5WCZX1WSdzveK8VDO3MWrHtYlb7PGEHDNd5/bUCSjZlMGq61RA,iv:A5QLdPjZPc2CDMluH70V4U5kjgMtqKidf4OAPx+s01A=,tag:9oaH0XQPztqdKskZ59JEZg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:uoGebIdkkYe8KoHFFxPpaj3ymaIvWK4QZg==,iv:oFrOcmmiQGVvKSs/EFqdo9WRdUgFZMIYM+DLv5614lU=,tag:IosqQWiKMIh/nV9IF1K4MA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:vGRyXrJb/H7NyXj69xI2yoLK1VU=,iv:7dKjm82RHq+5E1CBjlxS/wnzhqYluoZQrbgYGd4jYmk=,tag:+aBmFSt/+AEETFNqc7aobA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:7rl6lU6mAij0ZC5CUq+V25sgKlW1upT43lfwc/DgrnhQzzc9pLkwJA==,iv:dHhx6UD35GLahvSYhmZ0dZua4Nnx2qFJ1YUT2chJeKc=,tag:sulWLIrvGYyAsJ73ncDqvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MFZ2WVZkTTFBOEtxODZH
            MzFKT3JqWWhkajB1VWFLelRhdWxiY3FvWGhvCll1MERZMlVmdlY0eWhZcTFtUDZr
            WFE5L2RBdmJzeU4rNzR2WVg3c0hiNTAKLS0tIEdYUXFsNUtqQUVyR1EwNllQVHRT
            MWlPaFhMZEl1Mk8rN2NZV3IxQ1hUNnMK3tWR8Fw/GC45jHwtPZaS2Dgq0RiKiNGX
            G42qZua7otMy4PeMpCfOmoM/bVJXhKN1sgt/aFjBhwZWIOf2XrtpnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T17:52:22Z"
    mac: ENC[AES256_GCM,data:M2CQWqdzgmE1qFvhiaAnRn2Pa4djOYw+x4dSibV5R9oEdBpsmiYqstHWHOkla9hdAQZJtOXczUtvzFYf6SRxv/3JU1eenhqdbXgFf7pnnbtU9MnH6ZQAylETYKb1yx2S/OhgNNbOf0+Q3Iq9XA+A5gjZvGM/DtByuBO7up6+22Q=,iv:iOHQXNJfq+L6oTpeftjWtPGHoaWRHvx6fU+O5XR8n1U=,tag:ptU2ULG3LIpum2G8OrmG+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
