apiVersion: v1
kind: Secret
metadata:
    name: shared-secrets
stringData:
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:eFDkpQ2fGbVNHYrkiDURsn8=,iv:uryuCP8+onlmrPjxbNwRr4jOzlwTn9vkLrYDuGbIgCA=,tag:EGXwHg43rvViYR2F2RRX4w==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:Dok9Pw6nbyXEu7cs4bcxJ8XKy+kApS4VH2MieXdFAqdGKYu1R9M4cFCpYHCsKJEyQXXMjpc6rqUAfgO5D1xCLeqD2emh87zgtaKOerzUL49HizNL8Adh5GCS5LViuwogDCtucBPIwcuQbjCk34GAKfdG+KgkBLs0WhtU2+/c,iv:ukXXriM11STTrbWsfKKtdGXRlGCDo39CyM2jrP9DGdQ=,tag:uRmCKSV8WdqaRUPdkXxW7w==,type:str]
    SECRET_MINIO_ACCESSKEY: ENC[AES256_GCM,data:cFEIm7Mzb765t9aYRUfxqRrcDOY=,iv:vH2l32o4f8WHFgerj6BPEvKlgxG9skCtp0bKOmQNMcQ=,tag:MEq6Px8heMq7xGLqrOUgnQ==,type:str]
    SECRET_MINIO_SECRETKEY: ENC[AES256_GCM,data:qOK+HJtSEVEYKIHDr26NKk3LvkdNmuIeD1Bv9FPQrSQHgu2fI6kESQ==,iv:B2vlqstVU3pBtoitE8awQon9QZX1ba34zTEu3RNcArQ=,tag:2/8pVLkg+Ns2R6ajX6+nSA==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:n4+tTIZFQHW9H4CCLCk6Y12DZJSf,iv:GXERPGIJlEKejetouE4s/vLMmFGxMZheYNS9EQsmM4U=,tag:bicCTvz/FE55WeSzokqR7Q==,type:str]
    SECRET_AUTHELIA_DB_PASSWORD: ENC[AES256_GCM,data:MbbJrBDWgkgId8hWtVAjoMJYdI2zXXvS,iv:cDemkGjqRyTZU/X7HLjFLjtwxFp26ytyR92analxNm8=,tag:KcEP3QoGPEpUK3WttGQnmg==,type:str]
    SECRET_PAPERLESS_NGX_DB_PASSWORD: ENC[AES256_GCM,data:KU5CPBb817bKXDjUdg65XPo0PgWb7ynX,iv:pxLuLmHNC9SYlg8Hm1/62CGT/xNVk3dFHBFq+ufXmy4=,tag:dKcwWed4XTgUO89rDwMuDA==,type:str]
    SECRET_PAPERLESS_NGX_SECRET_KEY: ENC[AES256_GCM,data:Ry9DGDgptwcAG4Za+Xmi2fFF/dfCvD6rYf2d4u0Q9gg=,iv:+SRJ18ndlyO+pnWOUSP3pfGjGsGktOXevbtjGex5t38=,tag:tnuCgS3wRaTlTDWkKPsDWA==,type:str]
    SECRET_PAPERLESS_NGX_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:BspsipIwfiqo37/dHuyB+2PHWoaWMEonaPimdiYv9dDRf2icitrwQpQkhpycFf5p3YZtGhDvlFmyDyo6dEj1xqqZixMJ7mk2,iv:MpsW4CjaTfXJ/aM8jcptTy3lXxrBbemeXmyixc5R1AY=,tag:/fASnaPp9+Ef1Gn7KQc27Q==,type:str]
    SECRET_TANDOOR_RECEIPES_DB_PASSWORD: ENC[AES256_GCM,data:v5ACpPNQZnFADLSLl7gyFglpfa5Nn46a,iv:1UCYPOxS51AAHXXPGDKsFllAHLT9IM8xtxGPjDUiCMs=,tag:J0w1HcvtmkfIwn2vO+m4Kg==,type:str]
    SECRET_TANDOOR_RECEIPES_SECRET_KEY: ENC[AES256_GCM,data:95tKjHhbvlHCRmxNhzqsBRTdFSHzT9FpvMJMI1puOqT02KulpXVpKyOdKzEt3452mVs=,iv:vjLxS5f5Mxsl2fdgj90HPPp/JRZWmcqfTl4HqnWzSRI=,tag:V18zFVbp0xAAAiHwLBR0UA==,type:str]
    SECRET_TANDOOR_RECEIPES_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:+9Vp3un0AOA8G/rZ84faEwzH2q7sjj7N+RR2F+mAWvhWiy6/K+uCYPCm8NktYbBLoOtLF+gZOL19zOLNxJFbqrWuYG2PFreO,iv:CansCLrhxnRS1R2w/YUQEqE2tMXTw020mqNv2NnqT54=,tag:S2EZATefCzjl+4vuTBJVdQ==,type:str]
    SECRET_MEMOS_DB_PASSWORD: ENC[AES256_GCM,data:B9qBRho86QeROvPbetmY7tpl9mgQAzh4ny8EEfpeLVgzfri6DC5/ZQ==,iv:m4vqfQCS/AXLJYhQSVS3KIrPSg5dEld3W7PWZvfKBjE=,tag:bD8ZCr1s3CgvDAOH4HAvYg==,type:str]
    SECRET_IMMICH_DB_PASSWORD: ENC[AES256_GCM,data:RiMOzsUu7zqTLzVaxeXxeNgonYPWhkquI/r977oROodUYcRSSkAVqg==,iv:MgehUjqqrbkdf44W6LYt4rZQ1ZjrlEgyKuYTwWWOiVE=,tag:fDYX1RwaGjtHXD7R7OoxWw==,type:str]
    SECRET_SFTPGO_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:s33QyHXRjZrNMPTSt0ZpkK8IwXr4Kaf0kV9Q33igx/a9V8o5EfbxiQLbo40LKBMDTxR6X6jcwPC0/5qiDs+/KSwh7GuN13gW,iv:JAXuThWASoo4eRQVQHfs6BYum1bFn1yqy09Bko3y/j4=,tag:YYuJ1OoKQLpcgd8UUxeQMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OHZRQ1NEeDMwNHBxWGEy
            eWNUNzVDQ3BHVnhoRElWOWJMOTBaZ3k3cXlJCnlISjRsZEtpZW9rNG1oNGlmWm1I
            d3pZWlRjZ2ZBNXVnM3hTOU1zVlJEL0UKLS0tIGtZeXl1NVlmRnQyd2NRczNGVjRu
            WUpOM3VpbFhFeUIzMzZEOENVZ2h3Z2MKCgD/irjpJvN9/VpAbVaGg+fona5WZW+k
            RyXTiuhLa8i1zxZDpQDyy6cLpS37LSw9TZZbQK6On6DPz+SNLsAqcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-07T19:55:13Z"
    mac: ENC[AES256_GCM,data:0LfwrSBVYfI0ZDCZtCgRDWJCHbEp37RtE85zqWwkHRMCKxS031rzT72wvJ2KOdPSl60KDbKeuXMKguMEimtAp4oz9tHQpS7db4vTGCxBj5gKkan2KExeV/waXhkmJ2nQ9QSQL5IIHp9nsul+HGiNl0SEVSqGPubFzY0kXVFHkpU=,iv:vyakblUqiKsd/b/sMSRpHnv4F9mgFTuyZTtbahYmAgA=,tag:PlYZzKSzMG9I50dfP3WqoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
