apiVersion: v1
kind: Secret
metadata:
    name: restic-config-linkwarden-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Pq0bWSS79OLJJEkriVpWEvkPklWjmV/0pfN49gnxHTXdGadd0FJD0hPcHZPLhXGqVsMc9MdlbC2z/7lTO5SN+X9kCA==,iv:U7iwgpiiSXfglo/8pB2E6dc4+e+K9TGj+Pi/j0Xyxis=,tag:ir81hb/Eff9hAU/o4jcKcw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:jkOnvcXKXJhQ+TnrZllJplM2eVlqoVBXmA==,iv:PidYwbeSCYoQiJ2n0RDY5Dmxco9IFoB28xQ/jQ2UXik=,tag:8StqdaaeiHuwgJM8zykYAg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:9LwsihDm4t7KD37dg9IhtdWJhF4=,iv:waWCZYhbwmo77MG5Nhm6kXQ1rO+DI300BCW67Qi3mus=,tag:AZ3h+Ymy+N70Te27JOaRHg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:zLAYfiq4YoDQXlUetXlwkBWisclRAAYysTBbATENNA1PhaAuVJhgJA==,iv:N5Q8YEFWa4uXLdPTVX8/qwsg1JRC1BuuEsMvb4mN1nw=,tag:RRA34q0zK+zjVuRgwRmBGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuR24vREl6Z2pDQVlhVTR4
            RDBSUk1NVEIwbUR6b2k0akZoK0xJaU41UzNRClI0aTN5S0hMVDRGQWU3OFNyYytl
            d2pEZDNRVTJLRndTUmpoL25jbm9KcWMKLS0tIGtYd0hGdlE5eU5DQ1RQaVR6ZXlo
            NlA4R3B1TmNDUVFvWWR5cHZZQU94WFEKELVr3atm/Pml0Crsy1w9gNBKCICxgRZo
            nzAPIwMi4DEbRzlUfOuY1NY8ypVcrz6lbVCnemfQiPCvy2D4vf4tJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T13:31:48Z"
    mac: ENC[AES256_GCM,data:uS03eU7G0JIIFcF3BCQe+keJcUvh8EN/ePoEm/NRN6ddwzbB8LX9kyD8xb931tmmXzZMxh7iaK5NtRTORkc4p57lYXax2z6LYaagnT/KSACLZK36lCth3O5bj8UP9AI0/LuSlbbTSQbLlbXCdmP4h61ObVbgGMEJwOhq3DIVZQI=,iv:+ta1tpznLsC+kjrbE6lxWciVcAnwYkxqVePp9c/LYWY=,tag:+2G2PlzjilIbCy5tad9ajw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-linkwarden-postgresql
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:3XpGN/3mqcRjdwHp7p3qWEnog43Fso4KnsR8BStAsIfqw4smVvxhOyW0aEF0IAefpAaqKGK5n7/t4M1g1npL9bVHVS2Zo10rHw==,iv:gSa1CAXbLU97TGphRXfx5fyekDtC8hhvFlqX68RERsc=,tag:AkH8EHU7B0DLxmUzhS0Rvg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:GNGc3nxdcDnjjzr6bQGxMQSL7D4t45vlnQ==,iv:yGFAoet/wg64nCh/70Ni73VB8hrOXYqE01L17CjnNCk=,tag:zntot2MotA7/9pMpH6855Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:I0VwkTCGXEFzhZsIMPbBrJEzuK8=,iv:CpFfzrGBiIINAFD9QtBcC4BIY2hTPSREoHpLGMmvK3s=,tag:8WWYalpLNv7R8uuitoyI1A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:jywfVv2AmGZ0mbXcggSWa86yCzJP2R4i90EZw0tGb3D3yql+reJKfQ==,iv://1YKBk9A7ItN02mRhCJg893CfYL32kTAmTGTrf7OcA=,tag:Kdj7ddAFATkLp6wHQ4uFPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuR24vREl6Z2pDQVlhVTR4
            RDBSUk1NVEIwbUR6b2k0akZoK0xJaU41UzNRClI0aTN5S0hMVDRGQWU3OFNyYytl
            d2pEZDNRVTJLRndTUmpoL25jbm9KcWMKLS0tIGtYd0hGdlE5eU5DQ1RQaVR6ZXlo
            NlA4R3B1TmNDUVFvWWR5cHZZQU94WFEKELVr3atm/Pml0Crsy1w9gNBKCICxgRZo
            nzAPIwMi4DEbRzlUfOuY1NY8ypVcrz6lbVCnemfQiPCvy2D4vf4tJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T13:31:48Z"
    mac: ENC[AES256_GCM,data:uS03eU7G0JIIFcF3BCQe+keJcUvh8EN/ePoEm/NRN6ddwzbB8LX9kyD8xb931tmmXzZMxh7iaK5NtRTORkc4p57lYXax2z6LYaagnT/KSACLZK36lCth3O5bj8UP9AI0/LuSlbbTSQbLlbXCdmP4h61ObVbgGMEJwOhq3DIVZQI=,iv:+ta1tpznLsC+kjrbE6lxWciVcAnwYkxqVePp9c/LYWY=,tag:+2G2PlzjilIbCy5tad9ajw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
