apiVersion: v1
kind: Secret
metadata:
    name: restic-config-linkwarden-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:eSM0HIDS92jpfZ0LwbM6UZs+qIeU6+zUIhBYRkEe3PocRx0P0kWxr7xaOewfDlatRDlQf7LgVgANV6r9lAWEz0j05c5T,iv:H9jEWE6YQlb4j7QYkQYzBrr04N5ixx+4EWaJwTxJsno=,tag:umw2IarDtznGU7vEbU/DOg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:GNGc3nxdcDnjjzr6bQGxMQSL7D4t45vlnQ==,iv:yGFAoet/wg64nCh/70Ni73VB8hrOXYqE01L17CjnNCk=,tag:zntot2MotA7/9pMpH6855Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:FgZxiREC0zXbdqAbpAuUnWKPCTI=,iv:pKJecNVNFwRR9QVe7Y9qg1Yl6f0pWGQ2Jb91LM69zIM=,tag:tl0rHCODD49pU7tzT+cszA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BNe1OJ0dsSC07tJsghn7iXBrrxQzfAB86sRonUuO8Nxj0RimBDSuqA==,iv:qP1B4OiNLD2RgcLZtEr2YPJAWLxygbeiPKId0+L0nkQ=,tag:EDy49MA3DMDO6ndoQLas4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuR24vREl6Z2pDQVlhVTR4
            RDBSUk1NVEIwbUR6b2k0akZoK0xJaU41UzNRClI0aTN5S0hMVDRGQWU3OFNyYytl
            d2pEZDNRVTJLRndTUmpoL25jbm9KcWMKLS0tIGtYd0hGdlE5eU5DQ1RQaVR6ZXlo
            NlA4R3B1TmNDUVFvWWR5cHZZQU94WFEKELVr3atm/Pml0Crsy1w9gNBKCICxgRZo
            nzAPIwMi4DEbRzlUfOuY1NY8ypVcrz6lbVCnemfQiPCvy2D4vf4tJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:37:37Z"
    mac: ENC[AES256_GCM,data:iOvKrwUbRlovvkK3hAbvGt4jZwT8k2U5xeqizLcSPNnkKDPcZpNHOGIn1CSW8fWiT3LQc8cvZEBOYdVxKHX7njBs2i1VSAmE8AwMfv9Bxsj9PX6d8JNkqLyWnyF6c9nLqfkzGuhg4ovmCtx5J8B9iolteN9XdLfyh8MLiFnsDO4=,iv:tEh17q4jD7ca1BIP3ylUIpzLwO5r4NR9iCAo57ieWUs=,tag:BjpEqzYEF7okiC7vSjGy5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-linkwarden-postgresql
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Aehcqs45FkNOA7B1tTYfzX1RLPMKBNQGT+uvy1Nx6FcH/uS4QLSLxa8zniktE3/rCBfSuo4fxs6go7iUyO9L2KJ0MOG36cvV8nbO7dj7dY0=,iv:ZJ1RdyzgOslKi1faQuimji6NXK0kTaKM/N8pCqbaxIQ=,tag:t7I3uVKf/mzLVzO0N8LPUA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:GNGc3nxdcDnjjzr6bQGxMQSL7D4t45vlnQ==,iv:yGFAoet/wg64nCh/70Ni73VB8hrOXYqE01L17CjnNCk=,tag:zntot2MotA7/9pMpH6855Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:FgZxiREC0zXbdqAbpAuUnWKPCTI=,iv:pKJecNVNFwRR9QVe7Y9qg1Yl6f0pWGQ2Jb91LM69zIM=,tag:tl0rHCODD49pU7tzT+cszA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BNe1OJ0dsSC07tJsghn7iXBrrxQzfAB86sRonUuO8Nxj0RimBDSuqA==,iv:qP1B4OiNLD2RgcLZtEr2YPJAWLxygbeiPKId0+L0nkQ=,tag:EDy49MA3DMDO6ndoQLas4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuR24vREl6Z2pDQVlhVTR4
            RDBSUk1NVEIwbUR6b2k0akZoK0xJaU41UzNRClI0aTN5S0hMVDRGQWU3OFNyYytl
            d2pEZDNRVTJLRndTUmpoL25jbm9KcWMKLS0tIGtYd0hGdlE5eU5DQ1RQaVR6ZXlo
            NlA4R3B1TmNDUVFvWWR5cHZZQU94WFEKELVr3atm/Pml0Crsy1w9gNBKCICxgRZo
            nzAPIwMi4DEbRzlUfOuY1NY8ypVcrz6lbVCnemfQiPCvy2D4vf4tJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:37:37Z"
    mac: ENC[AES256_GCM,data:iOvKrwUbRlovvkK3hAbvGt4jZwT8k2U5xeqizLcSPNnkKDPcZpNHOGIn1CSW8fWiT3LQc8cvZEBOYdVxKHX7njBs2i1VSAmE8AwMfv9Bxsj9PX6d8JNkqLyWnyF6c9nLqfkzGuhg4ovmCtx5J8B9iolteN9XdLfyh8MLiFnsDO4=,iv:tEh17q4jD7ca1BIP3ylUIpzLwO5r4NR9iCAo57ieWUs=,tag:BjpEqzYEF7okiC7vSjGy5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
