apiVersion: v1
kind: Secret
metadata:
    name: restic-config-bind9-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:HDo64KZk/a9b0yV2B0y4xXsx7xRtfw65Q1buriCmkvtXlWH1O9Z49djtux98hYtnO1G8VyL3PqCMbqIhyv4=,iv:S0L9GqH11h6qVU8AMqpniIKyM27q230vDFlW/l+xffc=,tag:L9YvQNXRd6w1w0jNYXxDig==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:zirkWaZl8vqsSy5tOTb/6K2i0KsQ40mVLA==,iv:rIJDkeJDQ5LgvibaiHgwLYMerPn8FIauN0qN9QQH3bQ=,tag:Ecoo1VXdSVv470fIJgVb1A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:0El3ovvKTfdZN0X94lgsOaB7LFU=,iv:3a2+XSaGIuJOLV88vVUgI2UX/+12Kc/mJeH+BPQRMIk=,tag:qebEXyGyaybpBR3JUQxPtw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fs7D4NB6S9LAmuHEV5ec/PjTnu3xXLZYWeuNG1hJ2OHdm4K+KQ+DlQ==,iv:PP5tH/Z3EPNuR0mfvKtmZRfBv/OBYvxXDYpmThBOaGQ=,tag:ncx/M/C88FLrNpzmr6q6ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZHFZcmVBZ2tMb2E3TlFj
            bUZWOFRsR1cxUFpNUW1jejdMdGVmdGlHRWxzCmg2ZTBJZklCQkY4RUFvSGp2SGQ2
            WTVVTHRqMlBPWEo5QXU5TzM0VFJHS0kKLS0tIEtvK2w5Vmw1S3NKcWFXR3lCUGoz
            ZkVYbG43Q2c1VXZqTGxOZEU3UkNuNnMKkd/w/rlFcE0qTM2P+aRy8bkPVKy7kDMI
            eSigdjBnzVKL2TAAjv6RV4C7FNgpQJwbCXK6YkvTJ4S4GMxF90pE5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T13:24:28Z"
    mac: ENC[AES256_GCM,data:VPuruby4us3VPM0yWQwHFQjDt6YcKKeFs+DXfhlz0EKpfUC1IZUwG95/UqueTM1/ZHCA/aDiOMerGb+N9/yOYOS6xVuxAqx/mXlEXbCrIuPxLv9oJclXbCd3qx/maUqU0WXb7nX/3J/WeKNVJwtP5S841RcSBn5VBlvUmSXyImo=,iv:rMOdp+WSqVhkVToL7CwkdEznNK9BE+y1cuEkMmqMNmI=,tag:/t2650aDmM0vsD+0o/K4xA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
