apiVersion: v1
kind: Secret
metadata:
    name: restic-config-bind9-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:wcGG/WhZISIf6wVYZKm776XbgP+6QW3yxwpcB+7g2kuhfXCgGJsPO/hsVUxY5WtJdS+7btQM2tbbFJEU55NBIA==,iv:HvrJiPvWZKGbuq1zDvVuWspNWVPILAGYQla9vvesM0w=,tag:7bZYF9dtPFKYc5aEyHMyDw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:zirkWaZl8vqsSy5tOTb/6K2i0KsQ40mVLA==,iv:rIJDkeJDQ5LgvibaiHgwLYMerPn8FIauN0qN9QQH3bQ=,tag:Ecoo1VXdSVv470fIJgVb1A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Yb9B/1r3VBG6Y/TuTaQeAvaytJM=,iv:JvPiEtlI6wMwCp8ETYOCYHllv3FmK/JX3iMLN1LWI60=,tag://8ivwZR4hrobBX2X+ZVNA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rb8n/nqpq0xLD9ZMMTMWuHWos8tDczx3YHmyFVet90FxioJ/ecUcBA==,iv:yhluA+Kwb0sMOzBGPwKwquVbtqQyTfiRhxV6tM72AbQ=,tag:+XId7lL829Hcwp1ovSa00g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZHFZcmVBZ2tMb2E3TlFj
            bUZWOFRsR1cxUFpNUW1jejdMdGVmdGlHRWxzCmg2ZTBJZklCQkY4RUFvSGp2SGQ2
            WTVVTHRqMlBPWEo5QXU5TzM0VFJHS0kKLS0tIEtvK2w5Vmw1S3NKcWFXR3lCUGoz
            ZkVYbG43Q2c1VXZqTGxOZEU3UkNuNnMKkd/w/rlFcE0qTM2P+aRy8bkPVKy7kDMI
            eSigdjBnzVKL2TAAjv6RV4C7FNgpQJwbCXK6YkvTJ4S4GMxF90pE5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:35:38Z"
    mac: ENC[AES256_GCM,data:tBEGRgSlN9dZbnUaGHjxvvFCiGo5LyIElVYrZRK65I6YqoxzuoNxEaObcqUG5tLP6bmfG67rmwRCg/dv72Cq5D5DtrPlGmyZA7HB9Lo+1Zec3W1LUc3EEnt7i/e1lAtrW6rgdw/cXryNEJGmK8msnFelNUAuzzm4hez7tY8JYjE=,iv:JtNyinhrGNVxQsJPHQEF9fNDv79CA1Ahb6MrRpMt1HY=,tag:sa6fwW6lFwnZ0z3eAdqogQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
