apiVersion: v1
kind: Secret
metadata:
    name: restic-config-syncthing-config
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:bKpjkJPQH8FHEQ7WxfW9cylkRgQIa32hI32nGvlkwhhN9KeaecaIfNNixU6VLX09TDvBPF+ScZywwJNrvkVtbrthTAP9qQ==,iv:m+YQ7oo59r4Zyf6LwdmNMKfZE9VZC9MLtd1qT7ZXxb0=,tag:4Ud0zSinep7ajGTj/DyPmQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:AHj7rKUiLV8T8gLfHb82Pq7smQUyqWBMOg==,iv:Ym6PlsRIUM283cfpyxrnu6LOGtPXR2LhR9JAtlxPFDk=,tag:+pj8wnsmctbLnl6milkMuw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:U5kqoWF7qQfCN2XJEZ+V1EwSWZI=,iv:zwMm12Ht0IaT3sL11WUDE2XLXnN3LEDRzAX2cAFUxAU=,tag:P1xojSsAST1akLgaOaoA6Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Q0rxa+M1/2EiqHyzQiNR1HfIp/SFbFozsuPHtRtf32jk3h40AyN93A==,iv:zSfeleC9Rk25uX9GhGlepfdJJ92aICrtJ/YuahbgvCY=,tag:oNllmMlzUOUEgZG5N0GWJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTENGdXVMV1psRUJpSFlC
            Wm1EdUZtVExkOU02RzUvODJpWVBpZmlGQVE4CnlRQ2ZwemxrVlpYcU8wRmtKMU41
            VVgvRmEraGxZWFB0TklDL3hFYVhiQWsKLS0tIEkvK1F1V0ozeU1NWHF2cjlWbmxz
            djZJaGJSRHB4UVZFaGpodTU0Z1NJSmMKScjWzRO8+1UHSYTWLE9KAFvdvytvq4OP
            XA8XWTRJtuxus00pP5zoyePINclIIxGnjafp9SxY6+tBtKAxV2XStA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T15:09:38Z"
    mac: ENC[AES256_GCM,data:Hz57QaxmNdznNjIaZok6fwY0wzxTDGhFmcmAjA5ZZdFacgP+VQWvvkZzaxgTn42MsjCwZ/ImpUMZSK7FLa7+zHCXYN0qJYZNaQr/7hXfFGFlpdhd4wTVaEotO52EuVu+tnHT3OIhuijVavXkOmzHz3x2BqVG6gw1R8pa9ZEGtvA=,iv:iGI6L1Rayb3rUmdxutjYp/CcloBtXMzTQVVPAHX5W/0=,tag:R4QPo0D6qaAe4MKnSrYM8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-syncthing-files-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:IFUj5RUTsOELSLUxVWfBF97K1faOCqIbAzVF8MJwmoPe78/sZlLsLASp3nh8DXEsWXnO0W/8uGkIl+R+eEOi5iiY5wT9ses3,iv:mhwqcVZdfUsHeZcKFQ4mjx60uqS9PUlriaywskrU43I=,tag:0f6AdLlUFcobeySnBOnK9g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:AHj7rKUiLV8T8gLfHb82Pq7smQUyqWBMOg==,iv:Ym6PlsRIUM283cfpyxrnu6LOGtPXR2LhR9JAtlxPFDk=,tag:+pj8wnsmctbLnl6milkMuw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:yBZRkQgPKv0kduQnhe9K091UnaI=,iv:QeTGWuVeCZnejH76jz2ehr58IGvCV3+rbZ6eHl0g5Xg=,tag:fi4BP/eldgKsum4LCTgTHQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dLnSehUml2NtdR1HD0Lglee7XurJiy9LXqSfaTAYrH0RWuxGsJFNkA==,iv:0Y7mb2snO1culejJzWVNEAYLinaz5CCNZCD9ZCeWHfg=,tag:lpBcVsmMSXlmNwcnTPHUWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTENGdXVMV1psRUJpSFlC
            Wm1EdUZtVExkOU02RzUvODJpWVBpZmlGQVE4CnlRQ2ZwemxrVlpYcU8wRmtKMU41
            VVgvRmEraGxZWFB0TklDL3hFYVhiQWsKLS0tIEkvK1F1V0ozeU1NWHF2cjlWbmxz
            djZJaGJSRHB4UVZFaGpodTU0Z1NJSmMKScjWzRO8+1UHSYTWLE9KAFvdvytvq4OP
            XA8XWTRJtuxus00pP5zoyePINclIIxGnjafp9SxY6+tBtKAxV2XStA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T15:09:38Z"
    mac: ENC[AES256_GCM,data:Hz57QaxmNdznNjIaZok6fwY0wzxTDGhFmcmAjA5ZZdFacgP+VQWvvkZzaxgTn42MsjCwZ/ImpUMZSK7FLa7+zHCXYN0qJYZNaQr/7hXfFGFlpdhd4wTVaEotO52EuVu+tnHT3OIhuijVavXkOmzHz3x2BqVG6gw1R8pa9ZEGtvA=,iv:iGI6L1Rayb3rUmdxutjYp/CcloBtXMzTQVVPAHX5W/0=,tag:R4QPo0D6qaAe4MKnSrYM8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
