apiVersion: v1
kind: Secret
metadata:
    name: restic-config-syncthing-config
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:SUmQcTjPz6lpZ7pZwhoeYrBdiOnA8Ptsd8OkmL6a56DJsFUNlbjxu/yxzQQ/sFeMpmPXcIcLDXvC2tLMn00+WyREPTFRhw==,iv:ZjZ8yIRf0Ca2goTUKse+XD2mv4ipMl0w3FtMe8Q7ubY=,tag:rQvj9Bqa9n3CDyBC5KPE6A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:qfkvTEO5qG9PLIoK0vmpzCGr7/iA9u7ldw==,iv:sb120pFKHsBHG9mkqodE+hxsneRMVFJMatUPHEKBwPI=,tag:T+NRc3rG43WySuEoWCqNYg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Y2HbqyBMfHmyGbskCH4tEc3K2Tw=,iv:7WJCFr5BE6pMSsWrwDs2CBq5/HYQYCS812LE6qSAD1U=,tag:EGPDdB90Cc4e5O38TIqqkw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:k/o+vPLA0C8NUWzsrmTsIdWkz9CWWGpur+wPFjdQpsm4u7UqDTGkQw==,iv:/8TLGUPjy+dMUJgGdWxwVcAgkgxAEQGGQbwoQty7jPE=,tag:XRtKLdk7LsVAjJCEt7Oh1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0enRpVDFBMWhnS20rK2dh
            bVlIOGN6bWszYmpaYlFrTFhwcmJneHorZ2o4Ck5QUGpzd0ZjVnJSSldCS01LTXgv
            aHVmQ3pVUHQ1dGhyTXREL01uMVVhdWcKLS0tIFZXSkdUVC8wV09HTjdoa09acEp5
            QXZLUzJkNmdvMjNpYVhudkhoelVhc0EKym+tTcgRUO+LVWgk+kcqQHLhQ+H4FsLN
            QzngrdQLmB7gDyq5Aoh+3Lr+JtnxaPKqQJNltd1kiY0uI+FsUMB8oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T20:27:36Z"
    mac: ENC[AES256_GCM,data:C2Xu4v+lJHm1TbX8qyAHP9NmeZTi5sEpY7ivEtI9pryTJq058WNoO8yrDgNVtv0mCBQxYCtHAamYptJhZzhjesg4oKY++j39kcnEQ6BNgnO2gRtCtdfwY5WcVkvE+VrPFugEng9wvyH8eY/QlexpAVIpHCxw6scoLDuwdWiDKEM=,iv:2oYxueV1t1ygylxl5a41RPu5kSSx2EICTQyLjM0I+/k=,tag:NJNI8Q79ZHSlm6DfWBrs3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-syncthing-files-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:V+vbDMiGyDuxRGG0pPEQGhEkuXiFjGGOHPSJJP7CaZLPUeKOpTJUMYT2PuuQg/+Gm6YiIpQ9z/aaCBjbY/rSFw11JIBoDoScn2w=,iv:cVQC+QNqbhcCSbaCBDR2fi7UNr6WylqPXHtZby2oacY=,tag:dwoK7zJ3Ezr+O7xRRAzBUg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:ZlgL1I3++Jv2mQIQeMUYqv4t1r6bqUZy6g==,iv:NwOc2A+wCZR+CyG2a9he4lyJcQja52nWQvAdkzqx2Bw=,tag:RacLW/E82Ym9wsV/5uzeqA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:I1AYQRI9yJdAapGc/yyXjaLuBw8=,iv:lkPVZnHV0i7Al2cxSurWBWU5ivds8mO+kPr3MUIJlOw=,tag:WKp32E4bcyHKZzRrfZBKJA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:m08INI3kS+meyiheWE7EpCwHdEh1g3CLxGvM4DoMe++oAyrG7pY4iA==,iv:LJzUg3HxGvXWxvww4Z1bh4JYozE7QxyGQ5+O5ppy9mc=,tag:9felur7GuqQtRpygfop54w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0enRpVDFBMWhnS20rK2dh
            bVlIOGN6bWszYmpaYlFrTFhwcmJneHorZ2o4Ck5QUGpzd0ZjVnJSSldCS01LTXgv
            aHVmQ3pVUHQ1dGhyTXREL01uMVVhdWcKLS0tIFZXSkdUVC8wV09HTjdoa09acEp5
            QXZLUzJkNmdvMjNpYVhudkhoelVhc0EKym+tTcgRUO+LVWgk+kcqQHLhQ+H4FsLN
            QzngrdQLmB7gDyq5Aoh+3Lr+JtnxaPKqQJNltd1kiY0uI+FsUMB8oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T20:27:36Z"
    mac: ENC[AES256_GCM,data:C2Xu4v+lJHm1TbX8qyAHP9NmeZTi5sEpY7ivEtI9pryTJq058WNoO8yrDgNVtv0mCBQxYCtHAamYptJhZzhjesg4oKY++j39kcnEQ6BNgnO2gRtCtdfwY5WcVkvE+VrPFugEng9wvyH8eY/QlexpAVIpHCxw6scoLDuwdWiDKEM=,iv:2oYxueV1t1ygylxl5a41RPu5kSSx2EICTQyLjM0I+/k=,tag:NJNI8Q79ZHSlm6DfWBrs3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
