apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pvc-paperless-ngx.yaml
- pvc-postgresql.yaml
- pvc-redis.yaml
- hr-postgresql.yaml
- hr-redis.yaml
- hr-paperless-ngx.yaml
