---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pvc-paperless-ngx-consume.yaml
- pvc-paperless-ngx-data.yaml
- pvc-paperless-ngx-media.yaml
- pvc-postgresql.yaml
- hr-postgresql.yaml
- hr-redis.yaml
- hr-paperless-ngx.yaml
- volsync-restic-config-secret.sops.yaml
