apiVersion: v1
kind: Secret
metadata:
    name: restic-config-paperless-ngx-postgresql
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:qMlTCpEAIF89mmawvs3zKBf+wIAkJ87p5cQA9f9a6g03dtwmXXYm915R06oubX3LLYKr7eXmqVuHiveBhfCsLVALNMMG2RuMBcfxWA==,iv:0MY2j1sQi2PMK0CaOvLNuXzlM6KzQf4kSIX60hC5UNE=,tag:9QMku6gwC5wajPKhU+93Bw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:u/dmANyt3hlLwSNfTXL+5Q7aD+kJ0l6jCQ==,iv:pHyQDV6+TNaFJZYisYzli6hIS7wLDQuBlv39ZPy3MX8=,tag:gaLeIf/e3QHI5bvXWyQjCA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:XpVOPg+u4pJ0gbtsxGGflRxxkSE=,iv:Zi3O5DQietzgnCReHibDGSIl1+/bvBiYIgcOkB13MT0=,tag:7VKQLokv2r2S57N4kSi+1Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:f2tDxGpwU4pv4R9sLNuRuGSAqpN0xACcDKYcdX7BQx3ja/TdBs19pw==,iv:XvSshgZvqee2meJKCweh843UwcR3H7mHr+J4UH3DeXc=,tag:Yr9wTevyPxQZN8RCUNAt/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXanFlOXVLMXJYbkF6MFpH
            YUcyMWsxOEVxcm5qSEFOcG8zWHQ2UmUwNFE4ClRWVVp0UW1PVDBHUzlnemswb2hy
            bHdZN3dIeEhTV3hZNmJML202bHR1YVEKLS0tIG5IaHhaUnRib25nZmRaamNrbDVB
            UlI3MGJMY1ZHMUlEU1Jrb2lHVDZleDAK1mjJyBAguZOtN/DmI3ujoZxhDRScqZXI
            PMgdn2/8EoDBiiLNemvWV1jy6mSs4Hwm4eH+9la8DPt5BHxHcDZi+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T11:43:40Z"
    mac: ENC[AES256_GCM,data:b5dZyw5DPyBWCPXiGsP6rwK6+jNum8x9vgNczMMPcNZUjXc2XnAK381NeoLtlsL0PzZ1eW+Kyui5W1+4F6RgI597Q98sEYqBfZoVleQVtDpCCUnqQk1w8hu0xgIloEfl6X5xXOKxQR4mG8oiBkd4Rtp/m821a2JPlqwUc1FtXYA=,iv:kQdjcplylzWHzjyTojRV8yOIkP3UcPC2KFIffB57Y58=,tag:WlZbDnp1aYIPrXQ24+ixAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-paperless-ngx-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:5SAq2Oj24mVcBY6ZTSqyiYSb9PHP21fEbNnngORJuxD3gohu7c46wEFB7uv90DW8vepN90R+Mvibwo+cnbuDE6Aif6z9JQ==,iv:i5o7cwayPARkAxbNSVDcgj7DzuuXNGuP06kaVEE1QG8=,tag:CR+4z2Ekhw6yrTq/vW/HvA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:u/dmANyt3hlLwSNfTXL+5Q7aD+kJ0l6jCQ==,iv:pHyQDV6+TNaFJZYisYzli6hIS7wLDQuBlv39ZPy3MX8=,tag:gaLeIf/e3QHI5bvXWyQjCA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:XpVOPg+u4pJ0gbtsxGGflRxxkSE=,iv:Zi3O5DQietzgnCReHibDGSIl1+/bvBiYIgcOkB13MT0=,tag:7VKQLokv2r2S57N4kSi+1Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:f2tDxGpwU4pv4R9sLNuRuGSAqpN0xACcDKYcdX7BQx3ja/TdBs19pw==,iv:XvSshgZvqee2meJKCweh843UwcR3H7mHr+J4UH3DeXc=,tag:Yr9wTevyPxQZN8RCUNAt/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXanFlOXVLMXJYbkF6MFpH
            YUcyMWsxOEVxcm5qSEFOcG8zWHQ2UmUwNFE4ClRWVVp0UW1PVDBHUzlnemswb2hy
            bHdZN3dIeEhTV3hZNmJML202bHR1YVEKLS0tIG5IaHhaUnRib25nZmRaamNrbDVB
            UlI3MGJMY1ZHMUlEU1Jrb2lHVDZleDAK1mjJyBAguZOtN/DmI3ujoZxhDRScqZXI
            PMgdn2/8EoDBiiLNemvWV1jy6mSs4Hwm4eH+9la8DPt5BHxHcDZi+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T11:43:40Z"
    mac: ENC[AES256_GCM,data:b5dZyw5DPyBWCPXiGsP6rwK6+jNum8x9vgNczMMPcNZUjXc2XnAK381NeoLtlsL0PzZ1eW+Kyui5W1+4F6RgI597Q98sEYqBfZoVleQVtDpCCUnqQk1w8hu0xgIloEfl6X5xXOKxQR4mG8oiBkd4Rtp/m821a2JPlqwUc1FtXYA=,iv:kQdjcplylzWHzjyTojRV8yOIkP3UcPC2KFIffB57Y58=,tag:WlZbDnp1aYIPrXQ24+ixAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
