apiVersion: v1
kind: Secret
metadata:
    name: restic-config
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:cjOo/q5Djn9yXH3kKzhHm6+waBTbdERfzuFApF+RBDGtmTFTorPqrwiLSRZQWX9cnTUMJ4btUfi8Wdqx8u6lcVHZBFzIWg==,iv:TQq0hlGGCi6MHwIknsUI2/Rloewpr4pcm3CNYMn4HXo=,tag:yFA4+2IakENVb8drcIiP2g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:VBA3ZhyG1krIVe7NET/Ntp/zHcHwIi6wUA==,iv:HF4jpKHnfCvsplpKPzmnXLzVEOzNpCkt8U0Bqd8kMa8=,tag:n3Zm9jv0Uex6ZMsdlKMlxQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:393IhpPCnPfgS5fZCRJ9Aimal2o=,iv:mG+MJJqrhxK5aVZg71RJ7rN+tlpA0GZiMjg5MDx8zFo=,tag:fkhVNGSU5t/pOKs9sRiSuQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QjBzsjMXHrioCOWZBVS8AhpgZvDyp0jFdhqOAV/1I3OkPdFPiHtsCg==,iv:sYWv9YQ9QxZzHiXuN+cTycJqur9hoSCi6fEI4Yn4FL4=,tag:y8dxFFqIebMEHe9FlLnrtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVEZzUDJQNXd1NSsxU2l5
            U0tDaXpGcDhGVHVSdjhDNmdBSkk5WlkyS253CjV0bk8vWEk1R3dRTDEzVWRucXJO
            ME9jYUVYSUpNZUhkekgxT3ZNZ2NHSGcKLS0tIEVLMGczNGh5LzhsQTNIL1M1bVdE
            YTlNYUNQSXo3REpLUHV6eGlEeVkzNlUKXOYJhra9FzFn02Po7YakUEjPDS++nHvP
            yaE/fya721BMifrqcUCfWHzzxShcePFmvr+dUUKQlYJ7Nyuob5QuAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T19:56:53Z"
    mac: ENC[AES256_GCM,data:8QPUjigWSe58fzLHXz8/Rrowu/4N+6/f9V7jfREdLVAaMdh1JC7II1NZbxmlB3KY4WiNWc7VI962yDi6o2G69mr/0x1AWX936y0pl1r0B4CM1r48FQM8HS5qFPZFEW6huTyOCFV6ZDz2t1j7fLtwm2Llp5GYcUHA+ooDp+zgHSc=,iv:HLOSTBfjKEmYB1fn7CLs4MoTboghXaloudR2h9Z0wIk=,tag:Y+7RnEW9Nn3CEy4BoWQSSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
