apiVersion: v1
kind: Secret
metadata:
    name: restic-config-paperless-ngx-postgresql
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:OWBIDiTO2h7b/k2NvxArx+7R0uJqawFMKXSOjE4CTyq2c3pq011ydoGJaTBTVH9GmHq8CA+ZhfK4gi+CIyM4Hr9tq7UcwpgePoHQrrLLPGXCgZw=,iv:JlJ+RHjd2iLiL24P8WAaLPRr5Uwqg1ickOrizicROyw=,tag:xBA+C3wqMS+niuhmAwjDQA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:iV14N7DmAWU6q0iKtiuEUiaYArs6bcmKEA==,iv:nSfzi4HGUTiGnzUi/EJdQ8m7rR5CaY5LKbAgTfR64Gg=,tag:Iwt5nbTVQZaoTELEdJ5Wcg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:1p6zJFXbVSzJPdwU/62ri5MwYEw=,iv:jaleDdCAzOqRD39tYEh869vgocUv0WX68bEM1FSTOio=,tag:nNQvQI4NaPQ01YMqu74M/A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:MEeB/8AWpJhk06JLD+xvaf3+eWa8jwTXVpQ9cbVtXf81+sDMRhsVKw==,iv:kF0LgPq3NO3v3ApXz+HWT34t7AMP06g2VUX0JptECBU=,tag:YweDZTJfh3v6QC1XET7D2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcFgrazRuUWRTSW1uUWlp
            b2UzblY5Nm9FdzZNODMrZnd5b0N3UmxEZmhBCnlraVNoamU5RGc3TkV2bURFaVM3
            NnhtSGRONGdiUmtsSEwveE1OR2tCRzQKLS0tIHp0N0hTQUN0SzMxakdUZnVYV3A3
            bVBOSWEwV21DT2NhdlNuMkZOREw1SncK+CF8pIC4feFnOXx3HCOD1Q+MDBmNRiic
            6sYaTysyO6nnf7v+qc34Ap1sBOOvjbP2Oetf1cthBkNP7MyXrwY0rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T20:28:10Z"
    mac: ENC[AES256_GCM,data:Bixv2i8TjixX3zARGu4cDwMYwvmYtToPLTLiCuPv8/9vFQOr1iPhAAbN4j54BqlTUerpAa61oBlq8EdMWpy53QMovtddvIgmipI2GpX4bkQzBn731WRS6MVur8Jq71r2Uc8ws2DHOJ+NODLrcoNo+xeMnN/tpiIs7rJ4dBG2/dg=,iv:yQ5pNnAoxv3N8t8549ykZA2wZMSfEY1xU+gbNGOFIYc=,tag:bmnITahfWMyOeSJCWw6Njg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-paperless-ngx-media
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:sOTaUW8Mxx9bn/lQQdM+y+F5FOxawOHDYfgkxozkzTLF2AFKSpWHOXp4JfuhI946r8S1cApDBVDJOCSFQQ32Z+wxW4OOkGgmsQ==,iv:0femKVr5ptulX5rVBZ8ZTSUG0J4XGmqzcPatbnR8T+w=,tag:a9ItrGwF6NRFjDsH113GJA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:0PxwAqxqOE10sowMrLQp4WQpkAWUFiXJ3w==,iv:xbGvMblU8RM6MsPfArJ4jwAw8AI+qttXrvg22+KeFMI=,tag:XMdJGjmYvNv3OyrNFNSCyg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:LhSFoWfPCkgSW3qQ1ToG+IvaptI=,iv:uN2Jh3AS4SvCyFzt/3+4jYBMXRvMQaMqba5amTA1/vU=,tag:4z3PXuhqv4qzwSnwMuhgNg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lvUCQ78xy6XGB3KiIdKIkxyESRZ21JjBKZpvxFKHomNOYZvTQdzamg==,iv:DSLbxEwPIIKoLbCQrjzn4ScF+OgEuT1I40tKgIL4Lzc=,tag:4lummLCoHurHMOTzgZLcrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcFgrazRuUWRTSW1uUWlp
            b2UzblY5Nm9FdzZNODMrZnd5b0N3UmxEZmhBCnlraVNoamU5RGc3TkV2bURFaVM3
            NnhtSGRONGdiUmtsSEwveE1OR2tCRzQKLS0tIHp0N0hTQUN0SzMxakdUZnVYV3A3
            bVBOSWEwV21DT2NhdlNuMkZOREw1SncK+CF8pIC4feFnOXx3HCOD1Q+MDBmNRiic
            6sYaTysyO6nnf7v+qc34Ap1sBOOvjbP2Oetf1cthBkNP7MyXrwY0rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T20:28:10Z"
    mac: ENC[AES256_GCM,data:Bixv2i8TjixX3zARGu4cDwMYwvmYtToPLTLiCuPv8/9vFQOr1iPhAAbN4j54BqlTUerpAa61oBlq8EdMWpy53QMovtddvIgmipI2GpX4bkQzBn731WRS6MVur8Jq71r2Uc8ws2DHOJ+NODLrcoNo+xeMnN/tpiIs7rJ4dBG2/dg=,iv:yQ5pNnAoxv3N8t8549ykZA2wZMSfEY1xU+gbNGOFIYc=,tag:bmnITahfWMyOeSJCWw6Njg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-paperless-ngx-data
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:D9vpUxB7/welTV/nXk2mf8MCTSbrMHsudHyLNrn9HOEhQw47+Vdq3HHhmVbsOx6LPKH7RDUEEtBxCJGHlEnCw9Zhht5qlISC,iv:TI1Ipy3gbu/dFrjLyEq0KiVpVzD6hAgDCKQwflXRPOs=,tag:gKZTg+SEw7FqF7uziqTTXQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:LEGIOGJ83dmb2JpYXN2T9keVxeYw6URO5Q==,iv:2dnbEWxnkhG7q6Bq5IFKrFWmYYeOokORXtKYYqS8w+8=,tag:jx3ba7olqbhD8iWRDzqkVQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:67Ubzf7luVKdRe+5O6CY7Dz1N2k=,iv:vfC0QrqvVsO10fxAa/RYPxfuVOil8Dwlq3PjRu7e5sM=,tag:NpJlvsviswvruXbaTdHm0g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Vzm/s9byVZSfGJfQYSMclgD5r9TZ2OdF/MhIOmqt6VraJQ10wdYbZQ==,iv:t/BtYHraw+z5ifYu3L8n5ki3u4L+GzZZRd71ASefARE=,tag:8MktMyGhd+Hx+2F4qUWkPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcFgrazRuUWRTSW1uUWlp
            b2UzblY5Nm9FdzZNODMrZnd5b0N3UmxEZmhBCnlraVNoamU5RGc3TkV2bURFaVM3
            NnhtSGRONGdiUmtsSEwveE1OR2tCRzQKLS0tIHp0N0hTQUN0SzMxakdUZnVYV3A3
            bVBOSWEwV21DT2NhdlNuMkZOREw1SncK+CF8pIC4feFnOXx3HCOD1Q+MDBmNRiic
            6sYaTysyO6nnf7v+qc34Ap1sBOOvjbP2Oetf1cthBkNP7MyXrwY0rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T20:28:10Z"
    mac: ENC[AES256_GCM,data:Bixv2i8TjixX3zARGu4cDwMYwvmYtToPLTLiCuPv8/9vFQOr1iPhAAbN4j54BqlTUerpAa61oBlq8EdMWpy53QMovtddvIgmipI2GpX4bkQzBn731WRS6MVur8Jq71r2Uc8ws2DHOJ+NODLrcoNo+xeMnN/tpiIs7rJ4dBG2/dg=,iv:yQ5pNnAoxv3N8t8549ykZA2wZMSfEY1xU+gbNGOFIYc=,tag:bmnITahfWMyOeSJCWw6Njg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
