apiVersion: v1
kind: Secret
metadata:
    name: restic-config-paperless-ngx-postgresql
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:qRSk1m40q1U80tU2PLJXv7oR330DdlHVKwXoqheGHdBFpxD8TqqdVWzujuvc0oVA9JVqfS1BrFclQNg62FOKJMz2xzI4iB/HliEjvtuaBSIkZJ4=,iv:M/N+fCp19/ALHIpZMeYqCpAhGjmYrYQmnIvZ2ifwrDk=,tag:0quQyhjOqr7rpUTThZKhnw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:u/dmANyt3hlLwSNfTXL+5Q7aD+kJ0l6jCQ==,iv:pHyQDV6+TNaFJZYisYzli6hIS7wLDQuBlv39ZPy3MX8=,tag:gaLeIf/e3QHI5bvXWyQjCA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:MzUXbLME9YO0uwdRhcOdpiD0sE0=,iv:zAeLksT/Ei72Qv/6JzK/TzSVock9eEojOIPoxPmqSUM=,tag:LbPxOyuyWEJgg4sXIZneyQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hhcF2/nIWk+S671gK8GCAgEjZWw1SnMJ215/bUAOyYMcThpNax9qoQ==,iv:fAjyL03PzpIPbeTBFrqu6FNRl0NkRmwGMeXFeuVAA9k=,tag:FIj/p71NDaCcygOY2M8XaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXanFlOXVLMXJYbkF6MFpH
            YUcyMWsxOEVxcm5qSEFOcG8zWHQ2UmUwNFE4ClRWVVp0UW1PVDBHUzlnemswb2hy
            bHdZN3dIeEhTV3hZNmJML202bHR1YVEKLS0tIG5IaHhaUnRib25nZmRaamNrbDVB
            UlI3MGJMY1ZHMUlEU1Jrb2lHVDZleDAK1mjJyBAguZOtN/DmI3ujoZxhDRScqZXI
            PMgdn2/8EoDBiiLNemvWV1jy6mSs4Hwm4eH+9la8DPt5BHxHcDZi+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:38:12Z"
    mac: ENC[AES256_GCM,data:rAwcBJrHX/cCIjF0YSeJcZlzfi2lAEpMr73cxkD4vtFqW6q1POPa4B1gW/eHn7U0nXKeTmak85BPPtFmf5XMOfm52opaWYMuXrRh3lFzm1aO9fqmE2jQKA50P6JyBz6hotSGgu8O86mZZ9kymVDB95M2YC1K8eHwkUuY0eX1aiw=,iv:bOGk1MQdIjawEwLyWxa30k3gEAzbL/vbXftHYpqZ3Mg=,tag:44dltOBNZb7buUBGQPg+uQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
