# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jd2-config
# spec:
#   storageClassName: longhorn-backup
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   dataSourceRef:
#     kind: ReplicationDestination
#     apiGroup: volsync.backube
#     name: jd2-config-backup
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: jd2-config-backup
spec:
  sourcePVC: jd2 #-config
  trigger:
    schedule: "0 * * * *"
  restic:
    pruneIntervalDays: 7
    repository: restic-config-jd2-config
    retain:
      hourly: 4
      daily: 7
      weekly: 1
    copyMethod: Clone
    storageClassName: longhorn
    cacheStorageClassName: longhorn
    moverPodLabels:
      setGateway: "false"
# ---
# apiVersion: volsync.backube/v1alpha1
# kind: ReplicationDestination
# metadata:
#   name: jd2-config-backup
# spec:
#   trigger:
#     manual: restore-once
#   restic:
#     repository: restic-config-jd2-config
#     copyMethod: Snapshot
#     accessModes:
#     - ReadWriteOnce
#     capacity: 1Gi
#     cleanupCachePVC: true
#     cleanupTempPVC: true
#     enableFileDeletion: true
#     storageClassName: longhorn
#     cacheStorageClassName: longhorn
#     moverPodLabels:
#       setGateway: "false"
