apiVersion: v1
kind: Secret
metadata:
    name: restic-config-jd2-config
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:L1haM446rbTj+UcHugAcobGXq11JzDKVXVCfJnsh7/ixRwrT2cEaEYi3+PwRJaug1MP/xeUoOPXJu+Oydp2V0w==,iv:prFL104wCAjbZPDK/9wWsWP2xbh0q0RhMEJEyAQWP8Q=,tag:jzGPddB2xuX1pZx1YFDepA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:AHj7rKUiLV8T8gLfHb82Pq7smQUyqWBMOg==,iv:Ym6PlsRIUM283cfpyxrnu6LOGtPXR2LhR9JAtlxPFDk=,tag:+pj8wnsmctbLnl6milkMuw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TRW3OzPf/RzAth7aRtfpF2yyyc8=,iv:mQp9lIe3v4mnlujHyIH9MayCQyk4KKdtKW6sJypgVj0=,tag:5WY9INTmsuvDiBgBdm1wWA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3+Rus7fRRcOd9s/KrBJCPm4+Er/qwi+AJ43legXwdhRTCkvcfARsZQ==,iv:l/3uxUAfRnAwwn50+ppk46fwMLnSQz1SRCJIAmQj29w=,tag:+8DMDHKoJo7THHyNFa0YYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTENGdXVMV1psRUJpSFlC
            Wm1EdUZtVExkOU02RzUvODJpWVBpZmlGQVE4CnlRQ2ZwemxrVlpYcU8wRmtKMU41
            VVgvRmEraGxZWFB0TklDL3hFYVhiQWsKLS0tIEkvK1F1V0ozeU1NWHF2cjlWbmxz
            djZJaGJSRHB4UVZFaGpodTU0Z1NJSmMKScjWzRO8+1UHSYTWLE9KAFvdvytvq4OP
            XA8XWTRJtuxus00pP5zoyePINclIIxGnjafp9SxY6+tBtKAxV2XStA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:36:20Z"
    mac: ENC[AES256_GCM,data:yKNDMdIAbs/5RmEzCC+3cvt78vDGu3NTnT92GrKSDF1rbXyIBiKOUWc2VaRIoIG4rPGZw3XfaGXl0sNzlAZeCP/SmrIb+cUI75t3nD4XW2S3WwQ5+J4Ct76Bi3VelVIjzmwdHbwf4dB7HkF9ha+6ndsLKQRT6Xl/S3P7ybhyONA=,iv:wmbpiRDfSNYkk8ho1w8GujBwiuUOMi7+Ip1ZtuBbrKE=,tag:GlixImxYmE1oB7QutyADuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
